# Envoirement Setup

In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import sqlite3
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

In [2]:
sqliteConnection = sqlite3.connect('EmployeeProjectDB')
cursor = sqliteConnection.cursor()

In [3]:
def execute(query):
    cursor.execute(query)
    result = cursor.fetchall()
    for r in result:
        print(r)

# Creating table

## Patients Table

In [4]:
query = '''
CREATE TABLE Patients (
    PatientID INTEGER PRIMARY KEY AUTOINCREMENT,
    FirstName TEXT NOT NULL,
    LastName TEXT NOT NULL,
    City TEXT NOT NULL,
    InsurancePlanID INTEGER,
    FOREIGN KEY (InsurancePlanID) REFERENCES InsurancePlans(InsurancePlanID)
);
'''
execute(query)

## Doctors Table

In [5]:
query = '''
CREATE TABLE Doctors (
    DoctorID INTEGER PRIMARY KEY AUTOINCREMENT,
    FirstName TEXT NOT NULL,
    LastName TEXT NOT NULL,
    Specialty TEXT NOT NULL,
    HospitalID INTEGER,
    FOREIGN KEY (HospitalID) REFERENCES Hospitals(HospitalID)
);
'''
execute(query)

## Hospitals Table

In [6]:
query = '''
CREATE TABLE Hospitals (
    HospitalID INTEGER PRIMARY KEY AUTOINCREMENT,
    HospitalName TEXT NOT NULL,
    City TEXT NOT NULL
);
'''
execute(query)

## Procedures Table

In [7]:
query = '''
CREATE TABLE Procedures (
    ProcedureID INTEGER PRIMARY KEY AUTOINCREMENT,
    ProcedureName TEXT NOT NULL,
    Cost DECIMAL(10, 2) NOT NULL
);
'''
execute(query)

## InsurancePlans Table

In [8]:
query = '''
CREATE TABLE InsurancePlans (
    InsurancePlanID INTEGER PRIMARY KEY AUTOINCREMENT,
    PlanName TEXT NOT NULL,
    InsuranceProvider TEXT NOT NULL
);
'''
execute(query)

## Consultations Table

In [9]:
query = '''
CREATE TABLE Consultations (
    ConsultationID INTEGER PRIMARY KEY AUTOINCREMENT,
    PatientID INTEGER,
    DoctorID INTEGER,
    ProcedureID INTEGER,
    ConsultationDate DATE NOT NULL,
    FOREIGN KEY (PatientID) REFERENCES Patients(PatientID),
    FOREIGN KEY (DoctorID) REFERENCES Doctors(DoctorID),
    FOREIGN KEY (ProcedureID) REFERENCES Procedures(ProcedureID)
);
'''
execute(query)

## InsuranceClaims Table

In [10]:
query = '''
CREATE TABLE InsuranceClaims (
    ClaimID INTEGER PRIMARY KEY AUTOINCREMENT,
    PatientID INTEGER,
    ProcedureID INTEGER,
    ClaimDate DATE NOT NULL,
    FOREIGN KEY (PatientID) REFERENCES Patients(PatientID),
    FOREIGN KEY (ProcedureID) REFERENCES Procedures(ProcedureID)
);
'''
execute(query)

# Data insertion in tables

## Data for Patients

In [11]:
query = '''
INSERT INTO Patients (FirstName, LastName, City, InsurancePlanID) VALUES
('John', 'Doe', 'New York', 1),
('Jane', 'Smith', 'Los Angeles', 2),
('Alice', 'Brown', 'Chicago', 1),
('Bob', 'White', 'Houston', 3),
('Carol', 'Johnson', 'Phoenix', 2),
('David', 'Williams', 'Philadelphia', 1),
('Eve', 'Miller', 'San Antonio', 3),
('Frank', 'Davis', 'San Diego', 1),
('Grace', 'Garcia', 'Dallas', 4),
('Henry', 'Martinez', 'San Jose', 5),
('Ivy', 'Rodriguez', 'Austin', 1),
('Jack', 'Lopez', 'Jacksonville', 2),
('Kate', 'Gonzalez', 'Columbus', 3),
('Leo', 'Wilson', 'Charlotte', 4),
('Mia', 'Anderson', 'Indianapolis', 5),
('Nina', 'Thomas', 'Seattle', 3),
('Oscar', 'Taylor', 'Denver', 1),
('Paul', 'Hernandez', 'Washington', 4),
('Quinn', 'Moore', 'Boston', 5),
('Ryan', 'King', 'Nashville', 2);

'''
execute(query)

## Data for Doctors

In [12]:
query = '''
INSERT INTO Doctors (FirstName, LastName, Specialty, HospitalID) VALUES
('Dr. James', 'Smith', 'Cardiology', 1),
('Dr. Emily', 'Davis', 'Orthopedics', 2),
('Dr. Michael', 'Johnson', 'Dermatology', 1),
('Dr. Sarah', 'Lee', 'Neurology', 3),
('Dr. William', 'Miller', 'Pediatrics', 4),
('Dr. Linda', 'Brown', 'Cardiology', 5),
('Dr. Robert', 'Wilson', 'Orthopedics', 2),
('Dr. Barbara', 'Moore', 'Dermatology', 1),
('Dr. Richard', 'Taylor', 'Neurology', 3),
('Dr. Susan', 'Anderson', 'Pediatrics', 4),
('Dr. Joseph', 'Thomas', 'Cardiology', 5),
('Dr. Nancy', 'Martinez', 'Orthopedics', 1),
('Dr. Charles', 'Hernandez', 'Dermatology', 2),
('Dr. Lisa', 'Lopez', 'Neurology', 3),
('Dr. Daniel', 'Gonzalez', 'Pediatrics', 4),
('Dr. Patricia', 'Wilson', 'Cardiology', 5),
('Dr. Steven', 'Smith', 'Orthopedics', 2),
('Dr. Jessica', 'Jones', 'Dermatology', 1),
('Dr. Anthony', 'Garcia', 'Neurology', 3),
('Dr. Karen', 'Martinez', 'Pediatrics', 4);
'''
execute(query)

## Data for Hospitals

In [13]:
query = '''
INSERT INTO Hospitals (HospitalName, City) VALUES
('City General', 'New York'),
('Westside Medical', 'Los Angeles'),
('Eastside Clinic', 'Chicago'),
('Northern Health', 'Houston'),
('Southern Medical', 'Phoenix');
'''
execute(query)

## Data for Procedures

In [14]:
query = '''
INSERT INTO Procedures (ProcedureName, Cost) VALUES
('MRI Scan', 1500.00),
('X-Ray', 300.00),
('Blood Test', 100.00),
('Physical Therapy', 200.00),
('Cardiac Catheterization', 2500.00),
('Skin Biopsy', 500.00),
('CT Scan', 1200.00),
('Ultrasound', 600.00),
('Colonoscopy', 1800.00),
('Echocardiogram', 1300.00);
'''
execute(query)

## Insurance Plans

In [15]:
query = '''
INSERT INTO InsurancePlans (PlanName, InsuranceProvider) VALUES
('Plan A', 'Blue Shield'),
('Plan B', 'Aetna'),
('Plan C', 'United Healthcare'),
('Plan D', 'Cigna'),
('Plan E', 'Humana');
'''
execute(query)

## Consultations

In [16]:
query = '''
INSERT INTO Consultations (PatientID, DoctorID, ProcedureID, ConsultationDate) VALUES
(1, 1, 1, '2024-09-01'),
(2, 2, 2, '2024-09-02'),
(3, 3, 3, '2024-09-03'),
(4, 4, 4, '2024-09-04'),
(5, 5, 5, '2024-09-05'),
(6, 1, 6, '2024-09-06'),
(7, 2, 7, '2024-09-07'),
(8, 3, 8, '2024-09-08'),
(9, 4, 9, '2024-09-09'),
(10, 5, 10, '2024-09-10'),
(11, 1, 1, '2024-09-11'),
(12, 2, 2, '2024-09-12'),
(13, 3, 3, '2024-09-13'),
(14, 4, 4, '2024-09-14'),
(15, 5, 5, '2024-09-15'),
(16, 1, 6, '2024-09-16'),
(17, 2, 7, '2024-09-17'),
(18, 3, 8, '2024-09-18'),
(19, 4, 9, '2024-09-19'),
(20, 5, 10, '2024-09-20');

'''
execute(query)

## Data for Insurance Claims

In [17]:
query = '''
INSERT INTO InsuranceClaims (PatientID, ProcedureID, ClaimDate) VALUES
(1, 1, '2024-09-01'),
(2, 2, '2024-09-02'),
(3, 3, '2024-09-03'),
(4, 4, '2024-09-04'),
(5, 5, '2024-09-05'),
(6, 6, '2024-09-06'),
(7, 7, '2024-09-07'),
(8, 8, '2024-09-08'),
(9, 9, '2024-09-09'),
(10, 10, '2024-09-10'),
(11, 1, '2024-09-11'),
(12, 2, '2024-09-12'),
(13, 3, '2024-09-13'),
(14, 4, '2024-09-14'),
(15, 5, '2024-09-15'),
(16, 6, '2024-09-16'),
(17, 7, '2024-09-17'),
(18, 8, '2024-09-18'),
(19, 9, '2024-09-19'),
(20, 10, '2024-09-20');

'''
execute(query)

# Run Query

In [18]:
tables_query = "SELECT name FROM sqlite_master WHERE type='table';"
tables = pd.read_sql_query(tables_query, sqliteConnection)

for table in tables['name']:
    cursor = sqliteConnection.execute(f"PRAGMA table_info({table});")
    columns = cursor.fetchall()

    # Create a DataFrame for the current table's column info
    table_info_df = pd.DataFrame(columns, columns=['cid', 'Column Name', 'Data Type', 'Not Null', 'Default Value', 'Primary Key'])

    # Display the table name and its columns
    print(f"Table: {table}")
    display(table_info_df)
    print("\n")  # Add a newline for better readability
table_info_df

Table: Patients

   cid      Column Name Data Type  Not Null Default Value  Primary Key
0    0        PatientID   INTEGER         0          None            1
1    1        FirstName      TEXT         1          None            0
2    2         LastName      TEXT         1          None            0
3    3             City      TEXT         1          None            0
4    4  InsurancePlanID   INTEGER         0          None            0

Table: sqlite_sequence

   cid Column Name Data Type  Not Null Default Value  Primary Key
0    0        name                   0          None            0
1    1         seq                   0          None            0

Table: Doctors

   cid Column Name Data Type  Not Null Default Value  Primary Key
0    0    DoctorID   INTEGER         0          None            1
1    1   FirstName      TEXT         1          None            0
2    2    LastName      TEXT         1          None            0
3    3   Specialty      TEXT         1          None            0
4    4  HospitalID   INTEGER         0          None            0

Table: Hospitals

   cid   Column Name Data Type  Not Null Default Value  Primary Key
0    0    HospitalID   INTEGER         0          None            1
1    1  HospitalName      TEXT         1          None            0
2    2          City      TEXT         1          None            0

Table: Procedures

   cid    Column Name       Data Type  Not Null Default Value  Primary Key
0    0    ProcedureID         INTEGER         0          None            1
1    1  ProcedureName            TEXT         1          None            0
2    2           Cost  DECIMAL(10, 2)         1          None            0

Table: InsurancePlans

   cid        Column Name Data Type  Not Null Default Value  Primary Key
0    0    InsurancePlanID   INTEGER         0          None            1
1    1           PlanName      TEXT         1          None            0
2    2  InsuranceProvider      TEXT         1          None            0

Table: Consultations

   cid       Column Name Data Type  Not Null Default Value  Primary Key
0    0    ConsultationID   INTEGER         0          None            1
1    1         PatientID   INTEGER         0          None            0
2    2          DoctorID   INTEGER         0          None            0
3    3       ProcedureID   INTEGER         0          None            0
4    4  ConsultationDate      DATE         1          None            0

Table: InsuranceClaims

   cid  Column Name Data Type  Not Null Default Value  Primary Key
0    0      ClaimID   INTEGER         0          None            1
1    1    PatientID   INTEGER         0          None            0
2    2  ProcedureID   INTEGER         0          None            0
3    3    ClaimDate      DATE         1          None            0

   cid  Column Name Data Type  Not Null Default Value  Primary Key
0    0      ClaimID   INTEGER         0          None            1
1    1    PatientID   INTEGER         0          None            0
2    2  ProcedureID   INTEGER         0          None            0
3    3    ClaimDate      DATE         1          None            0

## Find pairs of patients treated by the same doctor.

In [19]:
query = '''
SELECT P1.firstname||" "||p1.lastname as P1_Name, P2.firstname||" "||p2.lastname as P2_Name, c1.doctorid
from consultations c1
join consultations c2 on c1.doctorid = c2.doctorid and c1.patientid< c2.patientid
join patients p1 on c1.patientid = p1.patientid
join patients p2 on c2.patientid = p2.patientid
;
'''
df = pd.read_sql_query(query, sqliteConnection)
df

           P1_Name         P2_Name  DoctorID
0         John Doe  David Williams         1
1         John Doe   Ivy Rodriguez         1
2         John Doe     Nina Thomas         1
3       Jane Smith      Eve Miller         2
4       Jane Smith      Jack Lopez         2
5       Jane Smith    Oscar Taylor         2
6      Alice Brown     Frank Davis         3
7      Alice Brown   Kate Gonzalez         3
8      Alice Brown  Paul Hernandez         3
9        Bob White    Grace Garcia         4
10       Bob White      Leo Wilson         4
11       Bob White     Quinn Moore         4
12   Carol Johnson  Henry Martinez         5
13   Carol Johnson    Mia Anderson         5
14   Carol Johnson       Ryan King         5
15  David Williams   Ivy Rodriguez         1
16  David Williams     Nina Thomas         1
17      Eve Miller      Jack Lopez         2
18      Eve Miller    Oscar Taylor         2
19     Frank Davis   Kate Gonzalez         3
20     Frank Davis  Paul Hernandez         3
21    Grace Garcia      Leo Wilson         4
22    Grace Garcia     Quinn Moore         4
23  Henry Martinez    Mia Anderson         5
24  Henry Martinez       Ryan King         5
25   Ivy Rodriguez     Nina Thomas         1
26      Jack Lopez    Oscar Taylor         2
27   Kate Gonzalez  Paul Hernandez         3
28      Leo Wilson     Quinn Moore         4
29    Mia Anderson       Ryan King         5

## Show combinations of all doctors and hospitals.

In [20]:
query = '''
SELECT d.firstname||" "||d.lastname as "Doctor_Name", h.Hospitalname
from doctors d
cross join hospitals h on d.hospitalid = h.hospitalid
order by h.Hospitalname;
'''
df = pd.read_sql_query(query, sqliteConnection)
df

              Doctor_Name      HospitalName
0         Dr. James Smith      City General
1     Dr. Michael Johnson      City General
2       Dr. Barbara Moore      City General
3      Dr. Nancy Martinez      City General
4       Dr. Jessica Jones      City General
5           Dr. Sarah Lee   Eastside Clinic
6      Dr. Richard Taylor   Eastside Clinic
7          Dr. Lisa Lopez   Eastside Clinic
8      Dr. Anthony Garcia   Eastside Clinic
9      Dr. William Miller   Northern Health
10     Dr. Susan Anderson   Northern Health
11    Dr. Daniel Gonzalez   Northern Health
12     Dr. Karen Martinez   Northern Health
13        Dr. Linda Brown  Southern Medical
14      Dr. Joseph Thomas  Southern Medical
15    Dr. Patricia Wilson  Southern Medical
16        Dr. Emily Davis  Westside Medical
17      Dr. Robert Wilson  Westside Medical
18  Dr. Charles Hernandez  Westside Medical
19       Dr. Steven Smith  Westside Medical

## Identify patients who have been treated multiple times by the same doctor.

## List all patients and their corresponding insurance plans.

In [21]:
query = '''
SELECT p.firstname||" "||p.lastname as "Patient_Name", PlanName, InsuranceProvider
from patients p
inner join insuranceplans i on p.insuranceplanid = i.insuranceplanid;
'''
df = pd.read_sql_query(query, sqliteConnection)
df

      Patient_Name PlanName  InsuranceProvider
0         John Doe   Plan A        Blue Shield
1       Jane Smith   Plan B              Aetna
2      Alice Brown   Plan A        Blue Shield
3        Bob White   Plan C  United Healthcare
4    Carol Johnson   Plan B              Aetna
5   David Williams   Plan A        Blue Shield
6       Eve Miller   Plan C  United Healthcare
7      Frank Davis   Plan A        Blue Shield
8     Grace Garcia   Plan D              Cigna
9   Henry Martinez   Plan E             Humana
10   Ivy Rodriguez   Plan A        Blue Shield
11      Jack Lopez   Plan B              Aetna
12   Kate Gonzalez   Plan C  United Healthcare
13      Leo Wilson   Plan D              Cigna
14    Mia Anderson   Plan E             Humana
15     Nina Thomas   Plan C  United Healthcare
16    Oscar Taylor   Plan A        Blue Shield
17  Paul Hernandez   Plan D              Cigna
18     Quinn Moore   Plan E             Humana
19       Ryan King   Plan B              Aetna

## Find patients who share the same insurance provider but live in different cities.

In [22]:
query = '''
SELECT p1.PatientID AS Patient1_ID,
       p2.PatientID AS Patient2_ID,
       p1.InsurancePlanID
FROM Patients p1
JOIN Patients p2
  ON p1.InsurancePlanID = p2.InsurancePlanID
  AND p1.City <> p2.City
  AND p1.PatientID < p2.PatientID;

'''
df = pd.read_sql_query(query, sqliteConnection)
df

    Patient1_ID  Patient2_ID  InsurancePlanID
0             1           11                1
1             1            3                1
2             1           17                1
3             1            6                1
4             1            8                1
5             2           12                2
6             2           20                2
7             2            5                2
8             3           11                1
9             3           17                1
10            3            6                1
11            3            8                1
12            4           13                3
13            4            7                3
14            4           16                3
15            5           12                2
16            5           20                2
17            6           11                1
18            6           17                1
19            6            8                1
20            7           13                3
21            7           16                3
22            8           11                1
23            8           17                1
24            9           14                4
25            9           18                4
26           10           19                5
27           10           15                5
28           11           17                1
29           12           20                2
30           13           16                3
31           14           18                4
32           15           19                5

## Show all combinations of doctors and the procedures they can perform.

In [23]:
query = '''
SELECT *
FROM doctors
cross join procedures;
'''
df = pd.read_sql_query(query, sqliteConnection)
print('The database is not optimise to proude the result which is relevent to real life. An orthopedist may not be able to perform cardio surgery.')
df

The database is not optimise to proude the result which is relevent to real life. An orthopedist may not be able to perform cardio surgery.

,DoctorID,FirstName,LastName,Specialty,HospitalID,ProcedureID,ProcedureName,Cost
0,1,Dr. James,Smith,Cardiology,1,1,MRI Scan,1500
1,1,Dr. James,Smith,Cardiology,1,2,X-Ray,300
2,1,Dr. James,Smith,Cardiology,1,3,Blood Test,100
3,1,Dr. James,Smith,Cardiology,1,4,Physical Therapy,200
4,1,Dr. James,Smith,Cardiology,1,5,Cardiac Catheterization,2500
...,...,...,...,...,...,...,...,...
195,20,Dr. Karen,Martinez,Pediatrics,4,6,Skin Biopsy,500
196,20,Dr. Karen,Martinez,Pediatrics,4,7,CT Scan,1200
197,20,Dr. Karen,Martinez,Pediatrics,4,8,Ultrasound,600
198,20,Dr. Karen,Martinez,Pediatrics,4,9,Colonoscopy,1800
199,20,Dr. Karen,Martinez,Pediatrics,4,10,Echocardiogram,1300

## Find patients who have consulted the same doctor for different ailments.

In [24]:
query = '''
SELECT c1.PatientID, c1.DoctorID, c1.ProcedureID, c2.ProcedureID
FROM Consultations c1
JOIN Consultations c2 ON c1.PatientID = c2.PatientID AND c1.DoctorID = c2.DoctorID AND c1.ProcedureID <> c2.ProcedureID;
'''
df = pd.read_sql_query(query, sqliteConnection)
df

Empty DataFrame
Columns: [PatientID, DoctorID, ProcedureID, ProcedureID]
Index: []

In [25]:
query = '''
SELECT *
FROM consultations c1
join consultations c2 on c1.doctorid = c2.doctorid and c1.procedureid <> c2.procedureid
order by c1.doctorid, c2.doctorid;

'''
df = pd.read_sql_query(query, sqliteConnection)
df

,ConsultationID,PatientID,DoctorID,ProcedureID,ConsultationDate,ConsultationID,PatientID,DoctorID,ProcedureID,ConsultationDate
0,1,1,1,1,2024-09-01,6,6,1,6,2024-09-06
1,1,1,1,1,2024-09-01,16,16,1,6,2024-09-16
2,6,6,1,6,2024-09-06,1,1,1,1,2024-09-01
3,6,6,1,6,2024-09-06,11,11,1,1,2024-09-11
4,11,11,1,1,2024-09-11,6,6,1,6,2024-09-06
5,11,11,1,1,2024-09-11,16,16,1,6,2024-09-16
6,16,16,1,6,2024-09-16,1,1,1,1,2024-09-01
7,16,16,1,6,2024-09-16,11,11,1,1,2024-09-11
8,2,2,2,2,2024-09-02,7,7,2,7,2024-09-07
9,2,2,2,2,2024-09-02,17,17,2,7,2024-09-17
10,7,7,2,7,2024-09-07,2,2,2,2,2024-09-02
11,7,7,2,7,2024-09-07,12,12,2,2,2024-09-12
12,12,12,2,2,2024-09-12,7,7,2,7,2024-09-07
13,12,12,2,2,2024-09-12,17,17,2,7,2024-09-17
14,17,17,2,7,2024-09-17,2,2,2,2,2024-09-02
15,17,17,2,7,2024-09-17,12,12,2,2,2024-09-12
16,3,3,3,3,2024-09-03,8,8,3,8,2024-09-08
17,3,3,3,3,2024-09-03,18,18,3,8,2024-09-18
18,8,8,3,8,2024-09-08,3,3,3,3,2024-09-03
19,8,8,3,8,2024-09-08,13,13,3,3,2024-09-13
20,13,13,3,3,2024-09-13,8,8,3,8,2024-09-08
21,13,13,3,3,2024-09-13,18,18,3,8,2024-09-18
22,18,18,3,8,2024-09-18,3,3,3,3,2024-09-03
23,18,18,3,8,2024-09-18,13,13,3,3,2024-09-13
24,4,4,4,4,2024-09-04,9,9,4,9,2024-09-09
25,4,4,4,4,2024-09-04,19,19,4,9,2024-09-19
26,9,9,4,9,2024-09-09,4,4,4,4,2024-09-04
27,9,9,4,9,2024-09-09,14,14,4,4,2024-09-14
28,14,14,4,4,2024-09-14,9,9,4,9,2024-09-09
29,14,14,4,4,2024-09-14,19,19,4,9,2024-09-19
30,19,19,4,9,2024-09-19,4,4,4,4,2024-09-04
31,19,19,4,9,2024-09-19,14,14,4,4,2024-09-14
32,5,5,5,5,2024-09-05,10,10,5,10,2024-09-10
33,5,5,5,5,2024-09-05,20,20,5,10,2024-09-20
34,10,10,5,10,2024-09-10,5,5,5,5,2024-09-05
35,10,10,5,10,2024-09-10,15,15,5,5,2024-09-15
36,15,15,5,5,2024-09-15,10,10,5,10,2024-09-10
37,15,15,5,5,2024-09-15,20,20,5,10,2024-09-20
38,20,20,5,10,2024-09-20,5,5,5,5,2024-09-05
39,20,20,5,10,2024-09-20,15,15,5,5,2024-09-15

## List all insurance claims along with patient and procedure details.

In [26]:
query = '''
SELECT
   i.ClaimID,
   p.FirstName || ' ' || p.LastName AS PatientName,
   pr.ProcedureName, i.ClaimDate
FROM insuranceclaims i
join patients p on i.PatientID = p.PatientID
join procedures pr on i.procedureid = pr.procedureid;
'''
df = pd.read_sql_query(query, sqliteConnection)
print('The intention of the query here is to get all the insurance claims \nfor which there is information available in patient and procedure \ntable, we would have used left join if we wanted to revtrive the \nclaims even if there is no matching record available in other tables.\n\n')
df

The intention of the query here is to get all the insurance claims
for which there is information available in patient and procedure
table, we would have used left join if we wanted to revtrive the
claims even if there is no matching record available in other tables.

    ClaimID     PatientName            ProcedureName   ClaimDate
0         1        John Doe                 MRI Scan  2024-09-01
1         2      Jane Smith                    X-Ray  2024-09-02
2         3     Alice Brown               Blood Test  2024-09-03
3         4       Bob White         Physical Therapy  2024-09-04
4         5   Carol Johnson  Cardiac Catheterization  2024-09-05
5         6  David Williams              Skin Biopsy  2024-09-06
6         7      Eve Miller                  CT Scan  2024-09-07
7         8     Frank Davis               Ultrasound  2024-09-08
8         9    Grace Garcia              Colonoscopy  2024-09-09
9        10  Henry Martinez           Echocardiogram  2024-09-10
10       11   Ivy Rodriguez                 MRI Scan  2024-09-11
11       12      Jack Lopez                    X-Ray  2024-09-12
12       13   Kate Gonzalez               Blood Test  2024-09-13
13       14      Leo Wilson         Physical Therapy  2024-09-14
14       15    Mia Anderson  Cardiac Catheterization  2024-09-15
15       16     Nina Thomas              Skin Biopsy  2024-09-16
16       17    Oscar Taylor                  CT Scan  2024-09-17
17       18  Paul Hernandez               Ultrasound  2024-09-18
18       19     Quinn Moore              Colonoscopy  2024-09-19
19       20       Ryan King           Echocardiogram  2024-09-20

## Identify doctors who treat patients from different cities but use the same procedure.

In [27]:
query = '''
SELECT
    c1.DoctorID,
    c1.ProcedureID,
    p1.City AS City1,
    p2.City AS City2
FROM
    consultations c1
JOIN
    consultations c2
    ON c1.doctorid = c2.doctorid
    AND c1.procedureid = c2.procedureid
JOIN
    patients p1
    ON c1.patientid = p1.patientid
JOIN
    patients p2
    ON c2.patientid = p2.patientid
    AND p1.city <> p2.city
    AND p1.patientid < p2.patientid;

'''
df = pd.read_sql_query(query, sqliteConnection)
df

   DoctorID  ProcedureID         City1         City2
0         1            1      New York        Austin
1         2            2   Los Angeles  Jacksonville
2         3            3       Chicago      Columbus
3         4            4       Houston     Charlotte
4         5            5       Phoenix  Indianapolis
5         1            6  Philadelphia       Seattle
6         2            7   San Antonio        Denver
7         3            8     San Diego    Washington
8         4            9        Dallas        Boston
9         5           10      San Jose     Nashville

## Generate a report showing doctors and their patients, including those who have not had consultations.

## Find patients who have never submitted an insurance claim.

## Show all possible combinations of patients and their potential treatments.

## Identify insurance plans that cover more than one patient.

## List all treatments covered by a specific insurance plan.

## Find doctors who share the same specialty but work in different hospitals.

**Practice Questions for Advanced Joins**:
- Find pairs of patients treated by the same doctor (SELF JOIN).
- Show combinations of all doctors and hospitals (CROSS JOIN).
- Identify patients who have been treated multiple times by the same doctor (SELF JOIN).
- List all patients and their corresponding insurance plans (INNER JOIN).
- Find patients who share the same insurance provider but live in different cities (SELF JOIN).
- Show all combinations of doctors and the procedures they can perform (CROSS JOIN).
- Find patients who have consulted the same doctor for different ailments (SELF JOIN).
- List all insurance claims along with patient and procedure details (MULTIPLE JOINS).
- Identify doctors who treat patients from different cities but use the same procedure (SELF JOIN).
- Generate a report showing doctors and their patients, including those who have not had consultations (LEFT JOIN).
- Find patients who have never submitted an insurance claim (LEFT JOIN).
- Show all possible combinations of patients and their potential treatments (CROSS JOIN).
- Identify insurance plans that cover more than one patient (SELF JOIN).
- List all treatments covered by a specific insurance plan (JOIN with FILTER).
- Find doctors who share the same specialty but work in different hospitals (SELF JOIN).