# Envoirement Setup

In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import sqlite3
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

In [2]:
sqliteConnection = sqlite3.connect('ecommerce_db')
cursor = sqliteConnection.cursor()

In [3]:
def execute(query):
    cursor.execute(query)
    result = cursor.fetchall()
    for r in result:
        print(r)

# Creating table

## Create table for Categories

In [4]:
query = '''
CREATE TABLE Categories (
    CategoryID INTEGER PRIMARY KEY,
    CategoryName TEXT NOT NULL
);
'''
execute(query)

## Create table for Customers

In [5]:
query = '''
CREATE TABLE Customers (
    CustomerID INTEGER PRIMARY KEY,
    FirstName TEXT NOT NULL,
    LastName TEXT NOT NULL,
    Email TEXT NOT NULL UNIQUE,
    Phone TEXT,
    Address TEXT,
    City TEXT,
    State TEXT,
    ZipCode TEXT,
    Country TEXT
);
'''
execute(query)

## Create table for Products

In [6]:
query = '''
CREATE TABLE Products (
    ProductID INTEGER PRIMARY KEY,
    ProductName TEXT NOT NULL,
    Description TEXT,
    Price REAL NOT NULL,
    StockQuantity INTEGER NOT NULL,
    CategoryID INTEGER,
    FOREIGN KEY (CategoryID) REFERENCES Categories(CategoryID)
);

'''
execute(query)

## Create table for Orders

In [7]:
query = '''
CREATE TABLE Orders (
    OrderID INTEGER PRIMARY KEY,
    CustomerID INTEGER,
    OrderDate TEXT NOT NULL,
    TotalAmount REAL NOT NULL,
    FOREIGN KEY (CustomerID) REFERENCES Customers(CustomerID)
);

'''
execute(query)

## Create table for OrderItems

In [8]:
query = '''
CREATE TABLE OrderItems (
    OrderItemID INTEGER PRIMARY KEY,
    OrderID INTEGER,
    ProductID INTEGER,
    Quantity INTEGER NOT NULL,
    Price REAL NOT NULL,
    FOREIGN KEY (OrderID) REFERENCES Orders(OrderID),
    FOREIGN KEY (ProductID) REFERENCES Products(ProductID)
);

'''
execute(query)

## Create table for Payments

In [9]:
query = '''
CREATE TABLE Payments (
    PaymentID INTEGER PRIMARY KEY,
    OrderID INTEGER,
    Amount REAL NOT NULL,
    PaymentMethod TEXT NOT NULL,
    PaymentStatus TEXT NOT NULL,
    FOREIGN KEY (OrderID) REFERENCES Orders(OrderID)
);
'''
execute(query)

## Create table for Reviews

In [10]:
query = '''
CREATE TABLE Reviews (
    ReviewID INTEGER PRIMARY KEY,
    ProductID INTEGER,
    CustomerID INTEGER,
    Rating INTEGER NOT NULL CHECK(Rating BETWEEN 1 AND 5),
    ReviewText TEXT,
    FOREIGN KEY (ProductID) REFERENCES Products(ProductID),
    FOREIGN KEY (CustomerID) REFERENCES Customers(CustomerID)
);
'''
execute(query)

# Enterting data into all the tables

## Insert data into Categories table

In [11]:
query = '''
INSERT INTO Categories (CategoryName) VALUES
('Electronics'),
('Clothing'),
('Books'),
('Home & Kitchen'),
('Sports');
'''
execute(query)

## Insert data into Customers table

In [12]:
query = '''
INSERT INTO Customers (FirstName, LastName, Email, Phone, Address, City, State, ZipCode, Country) VALUES
('Michael', 'Johnson', 'michaelj@example.com', '345-678-9012', '789 Maple St', 'Chicago', 'IL', '60601', 'USA'),
('Alice', 'Brown', 'aliceb@example.com', '456-789-0123', '101 Oak St', 'Houston', 'TX', '77001', 'USA'),
('David', 'Wilson', 'davidw@example.com', '567-890-1234', '202 Pine St', 'Phoenix', 'AZ', '85001', 'USA'),
('Emily', 'Davis', 'emilyd@example.com', '678-901-2345', '303 Cedar St', 'Philadelphia', 'PA', '19101', 'USA'),
('James', 'Garcia', 'jamesg@example.com', '789-012-3456', '404 Birch St', 'San Antonio', 'TX', '78201', 'USA'),
('Linda', 'Martinez', 'lindam@example.com', '890-123-4567', '505 Spruce St', 'San Diego', 'CA', '92101', 'USA'),
('Robert', 'Hernandez', 'roberth@example.com', '901-234-5678', '606 Redwood St', 'Dallas', 'TX', '75201', 'USA'),
('Patricia', 'Lopez', 'patricial@example.com', '012-345-6789', '707 Palm St', 'San Jose', 'CA', '95101', 'USA'),
('Charles', 'Gonzalez', 'charlesg@example.com', '123-456-7891', '808 Cypress St', 'Austin', 'TX', '73301', 'USA'),
('Barbara', 'Perez', 'barbarap@example.com', '234-567-8902', '909 Willow St', 'Jacksonville', 'FL', '32099', 'USA'),
('Daniel', 'Robinson', 'danielr@example.com', '345-678-9013', '1010 Poplar St', 'Fort Worth', 'TX', '76101', 'USA'),
('Jennifer', 'Clark', 'jenniferc@example.com', '456-789-0124', '1111 Fir St', 'Columbus', 'OH', '43085', 'USA'),
('Paul', 'Lewis', 'paull@example.com', '567-890-1235', '1212 Ash St', 'Charlotte', 'NC', '28201', 'USA'),
('Nancy', 'Walker', 'nancyw@example.com', '678-901-2346', '1313 Hemlock St', 'San Francisco', 'CA', '94101', 'USA'),
('Mark', 'Hall', 'markh@example.com', '789-012-3457', '1414 Beech St', 'Indianapolis', 'IN', '46201', 'USA'),
('Susan', 'Young', 'susany@example.com', '890-123-4568', '1515 Alder St', 'Seattle', 'WA', '98101', 'USA'),
('Joseph', 'Allen', 'josepha@example.com', '901-234-5679', '1616 Chestnut St', 'Denver', 'CO', '80201', 'USA'),
('Karen', 'King', 'karenk@example.com', '012-345-6790', '1717 Pinecone St', 'Boston', 'MA', '02101', 'USA');
'''
execute(query)

## Insert data into Products table

In [13]:
query = '''
INSERT INTO Products (ProductName, Description, Price, StockQuantity, CategoryID) VALUES
('Laptop', '15-inch laptop with 8GB RAM', 999.99, 30, 1),
('Tablet', '10-inch tablet with 64GB storage', 329.99, 40, 1),
('Jeans', 'Denim jeans with classic fit', 49.99, 70, 2),
('Dress', 'Summer dress with floral print', 29.99, 60, 2),
('Novel', 'Bestselling novel by a popular author', 14.99, 100, 3),
('Cookware Set', '10-piece nonstick cookware set', 79.99, 20, 4),
('Running Shoes', 'Lightweight running shoes', 59.99, 50, 5),
('Smartwatch', 'Fitness tracker with heart rate monitor', 199.99, 25, 1),
('Headphones', 'Noise-canceling over-ear headphones', 149.99, 40, 1),
('Coffee Maker', '12-cup programmable coffee maker', 89.99, 30, 4),
('Tennis Racket', 'Professional tennis racket', 129.99, 20, 5),
('Blender', 'High-performance blender', 99.99, 25, 4),
('Jacket', 'Waterproof winter jacket', 119.99, 45, 2),
('Smart TV', '50-inch 4K UHD Smart TV', 499.99, 15, 1),
('Bookcase', 'Wooden bookcase with 5 shelves', 149.99, 10, 4),
('Yoga Mat', 'Eco-friendly yoga mat', 29.99, 80, 5),
('E-reader', 'E-reader with 300ppi display', 129.99, 25, 1),
('Blouse', 'Silk blouse with button-down front', 39.99, 50, 2),
('Action Camera', '4K action camera with waterproof case', 249.99, 20, 1);
'''
execute(query)

## Insert data into Orders table

In [14]:
query = '''
INSERT INTO Orders (CustomerID, OrderDate, TotalAmount) VALUES
(3, '2024-09-03', 49.99),
(4, '2024-09-04', 29.99),
(5, '2024-09-05', 79.98),
(6, '2024-09-06', 39.99),
(7, '2024-09-07', 59.99),
(8, '2024-09-08', 149.99),
(9, '2024-09-09', 999.99),
(10, '2024-09-10', 89.99),
(11, '2024-09-11', 29.99),
(12, '2024-09-12', 99.99),
(13, '2024-09-13', 199.99),
(14, '2024-09-14', 14.99),
(15, '2024-09-15', 249.99),
(16, '2024-09-16', 499.99),
(17, '2024-09-17', 149.99),
(18, '2024-09-18', 79.99),
(19, '2024-09-19', 39.99),
(20, '2024-09-20', 999.99);
'''
execute(query)

## Insert data into OrderItems table

In [15]:
query = '''
INSERT INTO OrderItems (OrderID, ProductID, Quantity, Price) VALUES
(3, 3, 1, 49.99),
(4, 4, 1, 29.99),
(5, 5, 2, 39.99),
(6, 6, 1, 39.99),
(7, 7, 1, 59.99),
(8, 8, 1, 149.99),
(9, 9, 1, 999.99),
(10, 10, 1, 89.99),
(11, 11, 1, 29.99),
(12, 12, 1, 99.99),
(13, 13, 1, 199.99),
(14, 14, 1, 14.99),
(15, 15, 1, 249.99),
(16, 16, 1, 499.99),
(17, 17, 1, 149.99),
(18, 18, 1, 79.99),
(19, 19, 1, 39.99),
(20, 20, 1, 999.99);
'''
execute(query)

## Insert data into Payments table

In [16]:
query = '''
INSERT INTO Payments (OrderID, Amount, PaymentMethod, PaymentStatus) VALUES
(3, 49.99, 'Credit Card', 'Completed'),
(4, 29.99, 'PayPal', 'Completed'),
(5, 79.98, 'Credit Card', 'Completed'),
(6, 39.99, 'Credit Card', 'Completed'),
(7, 59.99, 'Credit Card', 'Completed'),
(8, 149.99, 'Credit Card', 'Completed'),
(9, 999.99, 'Credit Card', 'Completed'),
(10, 89.99, 'PayPal', 'Completed'),
(11, 29.99, 'Credit Card', 'Completed'),
(12, 99.99, 'Credit Card', 'Completed'),
(13, 199.99, 'Credit Card', 'Completed'),
(14, 14.99, 'Credit Card', 'Completed'),
(15, 249.99, 'PayPal', 'Completed'),
(16, 499.99, 'Credit Card', 'Completed'),
(17, 149.99, 'Credit Card', 'Completed'),
(18, 79.99, 'PayPal', 'Completed'),
(19, 39.99, 'Credit Card', 'Completed'),
(20, 999.99, 'Credit Card', 'Completed');
'''
execute(query)

## Insert data into Reviews table

In [17]:
query = '''
INSERT INTO Reviews (ProductID, CustomerID, Rating, ReviewText) VALUES
(3, 3, 4, 'Great fit and quality!'),
(4, 4, 5, 'Beautiful dress, love it!'),
(5, 5, 3, 'Good book but a bit slow-paced.'),
(6, 6, 4, 'Very useful in the kitchen.'),
(7, 7, 5, 'Comfortable and lightweight.'),
(8, 8, 5, 'Amazing smartwatch, highly recommend!'),
(9, 9, 5, 'Best headphones I have ever owned.'),
(10, 10, 4, 'Makes great coffee!'),
(11, 11, 4, 'Solid tennis racket.'),
(12, 12, 5, 'Fantastic blender!'),
(13, 13, 5, 'Warm and durable jacket.'),
(14, 14, 5, 'Stunning picture quality!'),
(15, 15, 4, 'Nice bookcase, easy to assemble.'),
(16, 16, 5, 'Love this yoga mat!'),
(17, 17, 4, 'Very handy e-reader.'),
(18, 18, 4, 'Stylish blouse, fits well.'),
(19, 19, 5, 'Great action camera for adventures!'),
(20, 20, 5, 'Fantastic laptop, super fast.');
'''
execute(query)

# Run Query

In [18]:
query = '''
SELECT *
FROM sqlite_master;
'''
df = pd.read_sql_query(query, sqliteConnection)
df

,type,name,tbl_name,rootpage,sql
0,table,Categories,Categories,2,CREATE TABLE Categories (\n CategoryID INTE...
1,table,Customers,Customers,3,CREATE TABLE Customers (\n CustomerID INTEG...
2,index,sqlite_autoindex_Customers_1,Customers,4,None
3,table,Products,Products,5,CREATE TABLE Products (\n ProductID INTEGER...
4,table,Orders,Orders,6,CREATE TABLE Orders (\n OrderID INTEGER PRI...
5,table,OrderItems,OrderItems,7,CREATE TABLE OrderItems (\n OrderItemID INT...
6,table,Payments,Payments,8,CREATE TABLE Payments (\n PaymentID INTEGER...
7,table,Reviews,Reviews,9,CREATE TABLE Reviews (\n ReviewID INTEGER P...

## Write a query to list all orders with customer information.

In [19]:
query = '''
SELECT *
FROM orders o inner join Customers c on o.CustomerID = c.CustomerID;
'''
df = pd.read_sql_query(query, sqliteConnection)
df

,OrderID,CustomerID,OrderDate,TotalAmount,CustomerID,FirstName,LastName,Email,Phone,Address,City,State,ZipCode,Country
0,1,3,2024-09-03,49.99,3,David,Wilson,davidw@example.com,567-890-1234,202 Pine St,Phoenix,AZ,85001,USA
1,2,4,2024-09-04,29.99,4,Emily,Davis,emilyd@example.com,678-901-2345,303 Cedar St,Philadelphia,PA,19101,USA
2,3,5,2024-09-05,79.98,5,James,Garcia,jamesg@example.com,789-012-3456,404 Birch St,San Antonio,TX,78201,USA
3,4,6,2024-09-06,39.99,6,Linda,Martinez,lindam@example.com,890-123-4567,505 Spruce St,San Diego,CA,92101,USA
4,5,7,2024-09-07,59.99,7,Robert,Hernandez,roberth@example.com,901-234-5678,606 Redwood St,Dallas,TX,75201,USA
5,6,8,2024-09-08,149.99,8,Patricia,Lopez,patricial@example.com,012-345-6789,707 Palm St,San Jose,CA,95101,USA
6,7,9,2024-09-09,999.99,9,Charles,Gonzalez,charlesg@example.com,123-456-7891,808 Cypress St,Austin,TX,73301,USA
7,8,10,2024-09-10,89.99,10,Barbara,Perez,barbarap@example.com,234-567-8902,909 Willow St,Jacksonville,FL,32099,USA
8,9,11,2024-09-11,29.99,11,Daniel,Robinson,danielr@example.com,345-678-9013,1010 Poplar St,Fort Worth,TX,76101,USA
9,10,12,2024-09-12,99.99,12,Jennifer,Clark,jenniferc@example.com,456-789-0124,1111 Fir St,Columbus,OH,43085,USA
10,11,13,2024-09-13,199.99,13,Paul,Lewis,paull@example.com,567-890-1235,1212 Ash St,Charlotte,NC,28201,USA
11,12,14,2024-09-14,14.99,14,Nancy,Walker,nancyw@example.com,678-901-2346,1313 Hemlock St,San Francisco,CA,94101,USA
12,13,15,2024-09-15,249.99,15,Mark,Hall,markh@example.com,789-012-3457,1414 Beech St,Indianapolis,IN,46201,USA
13,14,16,2024-09-16,499.99,16,Susan,Young,susany@example.com,890-123-4568,1515 Alder St,Seattle,WA,98101,USA
14,15,17,2024-09-17,149.99,17,Joseph,Allen,josepha@example.com,901-234-5679,1616 Chestnut St,Denver,CO,80201,USA
15,16,18,2024-09-18,79.99,18,Karen,King,karenk@example.com,012-345-6790,1717 Pinecone St,Boston,MA,02101,USA

## Find all customers with no orders.

In [20]:
query = '''
SELECT *
FROM Customers c left join orders o on o.CustomerID = c.CustomerID
where o.orderid is null;
'''
df = pd.read_sql_query(query, sqliteConnection)
df

,CustomerID,FirstName,LastName,Email,Phone,Address,City,State,ZipCode,Country,OrderID,CustomerID,OrderDate,TotalAmount
0,1,Michael,Johnson,michaelj@example.com,345-678-9012,789 Maple St,Chicago,IL,60601,USA,None,None,None,None
1,2,Alice,Brown,aliceb@example.com,456-789-0123,101 Oak St,Houston,TX,77001,USA,None,None,None,None

## List products that have not been ordered.

In [21]:
query = '''
SELECT p.ProductID, p.ProductName
FROM Products p left join OrderItems i on p.productid = i.productid
WHERE i.ProductID is null;
'''
df = pd.read_sql_query(query, sqliteConnection)
df

   ProductID ProductName
0          1      Laptop
1          2      Tablet

## Show all orders and products, even if they don't match.

In [22]:
query = '''
SELECT o.OrderID, o.ProductID, p.ProductName
FROM orderitems o left join products p on o.productid = p.productid

union

SELECT o.OrderID, o.ProductID, p.ProductName
FROM products p left join orderitems o on p.productid = o.productid
'''
df = pd.read_sql_query(query, sqliteConnection)
print('''Since SQLite does not support FULL OUTER JOIN this is a workaround we have used otherwise the FULL OUTER JOIN would have been as below.\n
SELECT o.OrderID, o.ProductID, p.ProductName\n
FROM OrderItems FULL OUTER JOIN Products p ON o.ProductID = p.ProductID;
''')
df

Since SQLite does not support FULL OUTER JOIN this is a workaround we have used otherwise the FULL OUTER JOIN would have been as below.

SELECT o.OrderID, o.ProductID, p.ProductName

FROM OrderItems FULL OUTER JOIN Products p ON o.ProductID = p.ProductID;

    OrderID  ProductID    ProductName
0       NaN        NaN         Laptop
1       NaN        NaN         Tablet
2       3.0        3.0          Jeans
3       4.0        4.0          Dress
4       5.0        5.0          Novel
5       6.0        6.0   Cookware Set
6       7.0        7.0  Running Shoes
7       8.0        8.0     Smartwatch
8       9.0        9.0     Headphones
9      10.0       10.0   Coffee Maker
10     11.0       11.0  Tennis Racket
11     12.0       12.0        Blender
12     13.0       13.0         Jacket
13     14.0       14.0       Smart TV
14     15.0       15.0       Bookcase
15     16.0       16.0       Yoga Mat
16     17.0       17.0       E-reader
17     18.0       18.0         Blouse
18     19.0       19.0  Action Camera
19     20.0       20.0           None

## Combine joins to create a report on orders and customer demographics.

In [23]:
query = '''
SELECT 
    c.CustomerID, 
    c.FirstName|| c.LastName as 'Customer Name', 
    c.Email, 
    o.orderid, 
    o.OrderDate, 
    o.TotalAmount, 
    p.PaymentMethod, 
    p.PaymentStatus, 
    pr.ProductName, 
    i.Quantity, 
    i.Price
FROM customers c left join orders o on c.customerID = o.customerid left join payments p on o.orderid = p.orderid left join orderitems i on o.orderid = i.orderid left join products pr on pr.ProductID = i.ProductID;
'''
df = pd.read_sql_query(query, sqliteConnection)
df

,CustomerID,Customer Name,Email,OrderID,OrderDate,TotalAmount,PaymentMethod,PaymentStatus,ProductName,Quantity,Price
0,1,MichaelJohnson,michaelj@example.com,NaN,None,NaN,None,None,None,NaN,NaN
1,2,AliceBrown,aliceb@example.com,NaN,None,NaN,None,None,None,NaN,NaN
2,3,DavidWilson,davidw@example.com,1.0,2024-09-03,49.99,None,None,None,NaN,NaN
3,4,EmilyDavis,emilyd@example.com,2.0,2024-09-04,29.99,None,None,None,NaN,NaN
4,5,JamesGarcia,jamesg@example.com,3.0,2024-09-05,79.98,Credit Card,Completed,Jeans,1.0,49.99
5,6,LindaMartinez,lindam@example.com,4.0,2024-09-06,39.99,PayPal,Completed,Dress,1.0,29.99
6,7,RobertHernandez,roberth@example.com,5.0,2024-09-07,59.99,Credit Card,Completed,Novel,2.0,39.99
7,8,PatriciaLopez,patricial@example.com,6.0,2024-09-08,149.99,Credit Card,Completed,Cookware Set,1.0,39.99
8,9,CharlesGonzalez,charlesg@example.com,7.0,2024-09-09,999.99,Credit Card,Completed,Running Shoes,1.0,59.99
9,10,BarbaraPerez,barbarap@example.com,8.0,2024-09-10,89.99,Credit Card,Completed,Smartwatch,1.0,149.99
10,11,DanielRobinson,danielr@example.com,9.0,2024-09-11,29.99,Credit Card,Completed,Headphones,1.0,999.99
11,12,JenniferClark,jenniferc@example.com,10.0,2024-09-12,99.99,PayPal,Completed,Coffee Maker,1.0,89.99
12,13,PaulLewis,paull@example.com,11.0,2024-09-13,199.99,Credit Card,Completed,Tennis Racket,1.0,29.99
13,14,NancyWalker,nancyw@example.com,12.0,2024-09-14,14.99,Credit Card,Completed,Blender,1.0,99.99
14,15,MarkHall,markh@example.com,13.0,2024-09-15,249.99,Credit Card,Completed,Jacket,1.0,199.99
15,16,SusanYoung,susany@example.com,14.0,2024-09-16,499.99,Credit Card,Completed,Smart TV,1.0,14.99
16,17,JosephAllen,josepha@example.com,15.0,2024-09-17,149.99,PayPal,Completed,Bookcase,1.0,249.99
17,18,KarenKing,karenk@example.com,16.0,2024-09-18,79.99,Credit Card,Completed,Yoga Mat,1.0,499.99

## Write a query to list all payments with order and customer details.

In [24]:
query = '''
SELECT *
FROM payments p inner join orders o on p.orderid = o.orderid inner join customers c on o.customerid = c.customerid;
'''
df = pd.read_sql_query(query, sqliteConnection)
df

,PaymentID,OrderID,Amount,PaymentMethod,PaymentStatus,OrderID,CustomerID,OrderDate,TotalAmount,CustomerID,FirstName,LastName,Email,Phone,Address,City,State,ZipCode,Country
0,1,3,49.99,Credit Card,Completed,3,5,2024-09-05,79.98,5,James,Garcia,jamesg@example.com,789-012-3456,404 Birch St,San Antonio,TX,78201,USA
1,2,4,29.99,PayPal,Completed,4,6,2024-09-06,39.99,6,Linda,Martinez,lindam@example.com,890-123-4567,505 Spruce St,San Diego,CA,92101,USA
2,3,5,79.98,Credit Card,Completed,5,7,2024-09-07,59.99,7,Robert,Hernandez,roberth@example.com,901-234-5678,606 Redwood St,Dallas,TX,75201,USA
3,4,6,39.99,Credit Card,Completed,6,8,2024-09-08,149.99,8,Patricia,Lopez,patricial@example.com,012-345-6789,707 Palm St,San Jose,CA,95101,USA
4,5,7,59.99,Credit Card,Completed,7,9,2024-09-09,999.99,9,Charles,Gonzalez,charlesg@example.com,123-456-7891,808 Cypress St,Austin,TX,73301,USA
5,6,8,149.99,Credit Card,Completed,8,10,2024-09-10,89.99,10,Barbara,Perez,barbarap@example.com,234-567-8902,909 Willow St,Jacksonville,FL,32099,USA
6,7,9,999.99,Credit Card,Completed,9,11,2024-09-11,29.99,11,Daniel,Robinson,danielr@example.com,345-678-9013,1010 Poplar St,Fort Worth,TX,76101,USA
7,8,10,89.99,PayPal,Completed,10,12,2024-09-12,99.99,12,Jennifer,Clark,jenniferc@example.com,456-789-0124,1111 Fir St,Columbus,OH,43085,USA
8,9,11,29.99,Credit Card,Completed,11,13,2024-09-13,199.99,13,Paul,Lewis,paull@example.com,567-890-1235,1212 Ash St,Charlotte,NC,28201,USA
9,10,12,99.99,Credit Card,Completed,12,14,2024-09-14,14.99,14,Nancy,Walker,nancyw@example.com,678-901-2346,1313 Hemlock St,San Francisco,CA,94101,USA
10,11,13,199.99,Credit Card,Completed,13,15,2024-09-15,249.99,15,Mark,Hall,markh@example.com,789-012-3457,1414 Beech St,Indianapolis,IN,46201,USA
11,12,14,14.99,Credit Card,Completed,14,16,2024-09-16,499.99,16,Susan,Young,susany@example.com,890-123-4568,1515 Alder St,Seattle,WA,98101,USA
12,13,15,249.99,PayPal,Completed,15,17,2024-09-17,149.99,17,Joseph,Allen,josepha@example.com,901-234-5679,1616 Chestnut St,Denver,CO,80201,USA
13,14,16,499.99,Credit Card,Completed,16,18,2024-09-18,79.99,18,Karen,King,karenk@example.com,012-345-6790,1717 Pinecone St,Boston,MA,02101,USA

## Find all orders that have not been paid for.

In [25]:
query = '''
SELECT *
FROM orders o  left join payments p on o.orderid = p.orderid
where p.paymentstatus is Null;
'''
df = pd.read_sql_query(query, sqliteConnection)
df

,OrderID,CustomerID,OrderDate,TotalAmount,PaymentID,OrderID,Amount,PaymentMethod,PaymentStatus
0,1,3,2024-09-03,49.99,None,None,None,None,None
1,2,4,2024-09-04,29.99,None,None,None,None,None

## List all products along with their reviews.

In [26]:
query = '''
SELECT p.ProductID, ProductName, Description, Price,Rating,ReviewText
FROM products p left join reviews r on p.productid = r.productid;
'''
df = pd.read_sql_query(query, sqliteConnection)
df

,ProductID,ProductName,Description,Price,Rating,ReviewText
0,1,Laptop,15-inch laptop with 8GB RAM,999.99,NaN,None
1,2,Tablet,10-inch tablet with 64GB storage,329.99,NaN,None
2,3,Jeans,Denim jeans with classic fit,49.99,4.0,Great fit and quality!
3,4,Dress,Summer dress with floral print,29.99,5.0,"Beautiful dress, love it!"
4,5,Novel,Bestselling novel by a popular author,14.99,3.0,Good book but a bit slow-paced.
5,6,Cookware Set,10-piece nonstick cookware set,79.99,4.0,Very useful in the kitchen.
6,7,Running Shoes,Lightweight running shoes,59.99,5.0,Comfortable and lightweight.
7,8,Smartwatch,Fitness tracker with heart rate monitor,199.99,5.0,"Amazing smartwatch, highly recommend!"
8,9,Headphones,Noise-canceling over-ear headphones,149.99,5.0,Best headphones I have ever owned.
9,10,Coffee Maker,12-cup programmable coffee maker,89.99,4.0,Makes great coffee!
10,11,Tennis Racket,Professional tennis racket,129.99,4.0,Solid tennis racket.
11,12,Blender,High-performance blender,99.99,5.0,Fantastic blender!
12,13,Jacket,Waterproof winter jacket,119.99,5.0,Warm and durable jacket.
13,14,Smart TV,50-inch 4K UHD Smart TV,499.99,5.0,Stunning picture quality!
14,15,Bookcase,Wooden bookcase with 5 shelves,149.99,4.0,"Nice bookcase, easy to assemble."
15,16,Yoga Mat,Eco-friendly yoga mat,29.99,5.0,Love this yoga mat!
16,17,E-reader,E-reader with 300ppi display,129.99,4.0,Very handy e-reader.
17,18,Blouse,Silk blouse with button-down front,39.99,4.0,"Stylish blouse, fits well."
18,19,Action Camera,4K action camera with waterproof case,249.99,5.0,Great action camera for adventures!

## Find all reviews without associated products.

In [27]:
query = '''
SELECT *
FROM reviews r left join products p on r.productid = p.productid
where p.productid is null;
'''
df = pd.read_sql_query(query, sqliteConnection)
df

,ReviewID,ProductID,CustomerID,Rating,ReviewText,ProductID,ProductName,Description,Price,StockQuantity,CategoryID
0,18,20,20,5,"Fantastic laptop, super fast.",None,None,None,None,None,None

## Show all order items with corresponding product and order information.

In [28]:
query = '''
SELECT  i.OrderItemID, i.OrderID, i.ProductID, i.Quantity, p.Price, p.ProductName, p.Description, o.CustomerID, o.OrderDate, o.TotalAmount
FROM orderitems i join products p on i.productid = p.productid join orders o on o.orderid = i.orderid;
'''
df = pd.read_sql_query(query, sqliteConnection)
df

,OrderItemID,OrderID,ProductID,Quantity,Price,ProductName,Description,CustomerID,OrderDate,TotalAmount
0,1,3,3,1,49.99,Jeans,Denim jeans with classic fit,5,2024-09-05,79.98
1,2,4,4,1,29.99,Dress,Summer dress with floral print,6,2024-09-06,39.99
2,3,5,5,2,14.99,Novel,Bestselling novel by a popular author,7,2024-09-07,59.99
3,4,6,6,1,79.99,Cookware Set,10-piece nonstick cookware set,8,2024-09-08,149.99
4,5,7,7,1,59.99,Running Shoes,Lightweight running shoes,9,2024-09-09,999.99
5,6,8,8,1,199.99,Smartwatch,Fitness tracker with heart rate monitor,10,2024-09-10,89.99
6,7,9,9,1,149.99,Headphones,Noise-canceling over-ear headphones,11,2024-09-11,29.99
7,8,10,10,1,89.99,Coffee Maker,12-cup programmable coffee maker,12,2024-09-12,99.99
8,9,11,11,1,129.99,Tennis Racket,Professional tennis racket,13,2024-09-13,199.99
9,10,12,12,1,99.99,Blender,High-performance blender,14,2024-09-14,14.99
10,11,13,13,1,119.99,Jacket,Waterproof winter jacket,15,2024-09-15,249.99
11,12,14,14,1,499.99,Smart TV,50-inch 4K UHD Smart TV,16,2024-09-16,499.99
12,13,15,15,1,149.99,Bookcase,Wooden bookcase with 5 shelves,17,2024-09-17,149.99
13,14,16,16,1,29.99,Yoga Mat,Eco-friendly yoga mat,18,2024-09-18,79.99
14,15,17,17,1,129.99,E-reader,E-reader with 300ppi display,19,2024-09-19,39.99
15,16,18,18,1,39.99,Blouse,Silk blouse with button-down front,20,2024-09-20,999.99

## List all orders with their payment status.

In [29]:
query = '''
SELECT o.OrderID, o.OrderDate, o.TotalAmount, p.PaymentStatus
FROM orders o left join payments p on o.OrderID = p.OrderID;
'''
df = pd.read_sql_query(query, sqliteConnection)
df

    OrderID   OrderDate  TotalAmount PaymentStatus
0         1  2024-09-03        49.99          None
1         2  2024-09-04        29.99          None
2         3  2024-09-05        79.98     Completed
3         4  2024-09-06        39.99     Completed
4         5  2024-09-07        59.99     Completed
5         6  2024-09-08       149.99     Completed
6         7  2024-09-09       999.99     Completed
7         8  2024-09-10        89.99     Completed
8         9  2024-09-11        29.99     Completed
9        10  2024-09-12        99.99     Completed
10       11  2024-09-13       199.99     Completed
11       12  2024-09-14        14.99     Completed
12       13  2024-09-15       249.99     Completed
13       14  2024-09-16       499.99     Completed
14       15  2024-09-17       149.99     Completed
15       16  2024-09-18        79.99     Completed
16       17  2024-09-19        39.99     Completed
17       18  2024-09-20       999.99     Completed

## Find all customers who have reviewed products.

In [30]:
query = '''
SELECT c.CustomerID, FirstName ||LastName as 'Customer Name', r.ProductID, Rating, ReviewText
FROM customers c inner join reviews r on c.CustomerID = r.CustomerID;
'''
df = pd.read_sql_query(query, sqliteConnection)
df

,CustomerID,Customer Name,ProductID,Rating,ReviewText
0,3,DavidWilson,3,4,Great fit and quality!
1,4,EmilyDavis,4,5,"Beautiful dress, love it!"
2,5,JamesGarcia,5,3,Good book but a bit slow-paced.
3,6,LindaMartinez,6,4,Very useful in the kitchen.
4,7,RobertHernandez,7,5,Comfortable and lightweight.
5,8,PatriciaLopez,8,5,"Amazing smartwatch, highly recommend!"
6,9,CharlesGonzalez,9,5,Best headphones I have ever owned.
7,10,BarbaraPerez,10,4,Makes great coffee!
8,11,DanielRobinson,11,4,Solid tennis racket.
9,12,JenniferClark,12,5,Fantastic blender!
10,13,PaulLewis,13,5,Warm and durable jacket.
11,14,NancyWalker,14,5,Stunning picture quality!
12,15,MarkHall,15,4,"Nice bookcase, easy to assemble."
13,16,SusanYoung,16,5,Love this yoga mat!
14,17,JosephAllen,17,4,Very handy e-reader.
15,18,KarenKing,18,4,"Stylish blouse, fits well."

## List all products that have never been reviewed.

In [31]:
query = '''
SELECT p.ProductID, p.ProductName, p.Price, p.Description
FROM products p left join reviews r on r.ProductID = p.ProductID
where r.ReviewID is null;
'''
df = pd.read_sql_query(query, sqliteConnection)
df

   ProductID ProductName   Price                       Description
0          1      Laptop  999.99       15-inch laptop with 8GB RAM
1          2      Tablet  329.99  10-inch tablet with 64GB storage

## Show all categories with the products they contain.

In [32]:
query = '''
SELECT CategoryName, ProductName
FROM categories c left join products p on c.CategoryID = p.CategoryID;
'''
df = pd.read_sql_query(query, sqliteConnection)
df

      CategoryName    ProductName
0      Electronics  Action Camera
1      Electronics       E-reader
2      Electronics     Headphones
3      Electronics         Laptop
4      Electronics       Smart TV
5      Electronics     Smartwatch
6      Electronics         Tablet
7         Clothing         Blouse
8         Clothing          Dress
9         Clothing         Jacket
10        Clothing          Jeans
11           Books          Novel
12  Home & Kitchen        Blender
13  Home & Kitchen       Bookcase
14  Home & Kitchen   Coffee Maker
15  Home & Kitchen   Cookware Set
16          Sports  Running Shoes
17          Sports  Tennis Racket
18          Sports       Yoga Mat

## List orders and their items, showing even if an item is missing from the order.

In [33]:
query = '''
SELECT o.OrderID, o.OrderDate, o.CustomerID, i.ProductID, i.Quantity, i.Price
FROM orders o left join orderitems i on o.orderid = i.orderid;
'''
df = pd.read_sql_query(query, sqliteConnection)
df

    OrderID   OrderDate  CustomerID  ProductID  Quantity   Price
0         1  2024-09-03           3        NaN       NaN     NaN
1         2  2024-09-04           4        NaN       NaN     NaN
2         3  2024-09-05           5        3.0       1.0   49.99
3         4  2024-09-06           6        4.0       1.0   29.99
4         5  2024-09-07           7        5.0       2.0   39.99
5         6  2024-09-08           8        6.0       1.0   39.99
6         7  2024-09-09           9        7.0       1.0   59.99
7         8  2024-09-10          10        8.0       1.0  149.99
8         9  2024-09-11          11        9.0       1.0  999.99
9        10  2024-09-12          12       10.0       1.0   89.99
10       11  2024-09-13          13       11.0       1.0   29.99
11       12  2024-09-14          14       12.0       1.0   99.99
12       13  2024-09-15          15       13.0       1.0  199.99
13       14  2024-09-16          16       14.0       1.0   14.99
14       15  2024-09-17          17       15.0       1.0  249.99
15       16  2024-09-18          18       16.0       1.0  499.99
16       17  2024-09-19          19       17.0       1.0  149.99
17       18  2024-09-20          20       18.0       1.0   79.99