## SQLite setup

In [1]:
import sqlite3
import pandas as pd

In [2]:
#creating a database

sqliteConnection = sqlite3.connect('CompanyDB.db')

In [3]:
#creating a cursor to execute queries

cursor = sqliteConnection.cursor()

In [4]:
# Test query to make sure everything working fine.

query = 'select sqlite_version();'
cursor.execute(query)
result = cursor.fetchall()
print(result)

[('3.32.3',)]

#### execute

In [5]:
def execute(query):
    cursor.execute(query)
    result = cursor.fetchall()
    for r in result:
        print(r)

#### executedf

In [6]:
def executedf(query):
    df = pd.read_sql_query(query, sqliteConnection)
    print(df.to_string(index=False))

#### executedf_index

In [7]:
def executedf_index(query):
    df = pd.read_sql_query(query, sqliteConnection)

## **Creating Tables**

#### Creating Employees Table

In [8]:
# creating Employees table

query ='''
CREATE TABLE Employees (
    EmployeeID INTEGER PRIMARY KEY AUTOINCREMENT,
    FirstName TEXT NOT NULL,
    LastName TEXT NOT NULL,
    Gender TEXT CHECK(Gender IN ('Male', 'Female', 'Other')),
    BirthDate DATE,
    HireDate DATE,
    DepartmentID INTEGER,
    SalaryID INTEGER,
    ManagerID INTEGER,
    FOREIGN KEY (DepartmentID) REFERENCES Departments(DepartmentID),
    FOREIGN KEY (SalaryID) REFERENCES Salaries(SalaryID),
    FOREIGN KEY (ManagerID) REFERENCES Employees(EmployeeID)
);
'''
execute(query)

#### Creating Departments Table

In [9]:
# creating Departments table

query ='''
CREATE TABLE Departments (
    DepartmentID INTEGER PRIMARY KEY AUTOINCREMENT,
    DepartmentName TEXT NOT NULL,
    Location TEXT
);
'''

execute(query)

#### Creating Projects Table

In [10]:
# creating Projects table

query ='''
CREATE TABLE Projects (
    ProjectID INTEGER PRIMARY KEY AUTOINCREMENT,
    ProjectName TEXT NOT NULL,
    StartDate DATE,
    EndDate DATE,
    DepartmentID INTEGER,
    FOREIGN KEY (DepartmentID) REFERENCES Departments(DepartmentID)
);
'''

execute(query)

#### Creating Salaries Table

In [11]:
# creating Salaries table

query ='''
CREATE TABLE Salaries (
    SalaryID INTEGER PRIMARY KEY AUTOINCREMENT,
    BaseSalary REAL NOT NULL,
    Bonus REAL,
    EmployeeID INTEGER,
    FOREIGN KEY (EmployeeID) REFERENCES Employees(EmployeeID)
);
'''

execute(query)

#### Creating Timesheets Table

In [12]:
# creating Timesheets table

query ='''
CREATE TABLE Timesheets (
    TimesheetID INTEGER PRIMARY KEY AUTOINCREMENT,
    EmployeeID INTEGER,
    ProjectID INTEGER,
    WorkDate DATE,
    HoursWorked REAL,
    FOREIGN KEY (EmployeeID) REFERENCES Employees(EmployeeID),
    FOREIGN KEY (ProjectID) REFERENCES Projects(ProjectID)
);
'''

execute(query)

## **Inserting data into tables**

#### Insert initial data into Departments

In [13]:
# Insert initial data into Departments

query ='''
INSERT INTO Departments (DepartmentName, Location) VALUES
('Human Resources', 'New York'),
('Finance', 'San Francisco'),
('Engineering', 'Austin'),
('Marketing', 'Chicago');

'''
execute(query)

#### Insert initial data into Employees

In [14]:
# Insert initial data into Employees

query ='''
-- Insert more data into Employees table with varied ManagerID and DepartmentID
INSERT INTO Employees (FirstName, LastName, Gender, BirthDate, HireDate, DepartmentID, SalaryID, ManagerID) VALUES
-- Management
('John', 'Doe', 'Male', '1985-05-15', '2010-06-01', 3, 1, NULL),  -- John is a manager (Engineering)
('Bob', 'Brown', 'Male', '1978-03-25', '2005-11-30', 2, 2, NULL),  -- Bob is a manager (Finance)
('Alice', 'Johnson', 'Female', '1982-01-14', '2008-04-22', 4, 3, NULL),  -- Alice is a manager (Marketing)
('Susan', 'Clark', 'Female', '1979-10-02', '2006-07-15', 1, 4, NULL),  -- Susan is a manager (HR)

-- Engineering Department
('Michael', 'Davis', 'Male', '1992-03-11', '2016-01-18', 3, 5, 1),  -- Reports to John Doe
('Emily', 'Wilson', 'Female', '1994-05-23', '2018-03-25', 3, 6, 1),  -- Reports to John Doe
('David', 'Martinez', 'Male', '1987-11-12', '2012-07-01', 3, 7, 1),  -- Reports to John Doe

-- Finance Department
('Laura', 'Taylor', 'Female', '1989-08-19', '2013-10-09', 2, 8, 2),  -- Reports to Bob Brown
('James', 'Anderson', 'Male', '1986-02-28', '2009-04-03', 2, 9, 2),  -- Reports to Bob Brown
('Patricia', 'Thomas', 'Female', '1991-12-22', '2017-11-05', 2, 10, 2),  -- Reports to Bob Brown

-- Marketing Department
('Karen', 'Moore', 'Female', '1983-07-14', '2011-09-17', 4, 11, 3),  -- Reports to Alice Johnson
('Robert', 'Jackson', 'Male', '1990-06-30', '2015-12-11', 4, 12, 3),  -- Reports to Alice Johnson
('Lisa', 'White', 'Female', '1988-04-27', '2014-06-22', 4, 13, 3),  -- Reports to Alice Johnson

-- Human Resources Department
('Brian', 'Harris', 'Male', '1981-09-07', '2007-05-20', 1, 14, 4),  -- Reports to Susan Clark
('Jennifer', 'Martin', 'Female', '1993-01-09', '2017-08-14', 1, 15, 4),  -- Reports to Susan Clark
('William', 'Thompson', 'Male', '1985-12-13', '2010-10-30', 1, 16, 4);  -- Reports to Susan Clark

'''
cursor.execute(query)

#### Insert initial data into Projects

In [15]:
# Insert initial data into Projects

query ='''
-- Insert data into Projects table
INSERT INTO Projects (ProjectName, StartDate, EndDate, DepartmentID) VALUES
('Website Redesign', '2023-01-15', '2023-06-30', 4),   -- Marketing and Engineering
('Financial Audit', '2023-02-01', '2023-03-31', 2),    -- Finance
('HR System Upgrade', '2023-05-01', '2023-08-15', 1),  -- HR
-- Additional Projects
('Cloud Migration', '2023-03-01', '2023-09-30', 3),    -- Engineering
('Market Research', '2023-04-01', '2023-07-31', 4);    -- Marketing

'''

execute(query)

#### Insert initial data into Salaries

In [16]:
# Insert initial data into Salaries

query ='''
-- Insert data into Salaries table corresponding to the updated Employees table
INSERT INTO Salaries (BaseSalary, Bonus, EmployeeID) VALUES
-- Salaries for Management
(120000, 15000, 1),  -- John Doe
(115000, 14000, 2),  -- Bob Brown
(110000, 13000, 3),  -- Alice Johnson
(105000, 12000, 4),  -- Susan Clark

-- Salaries for Engineering Department
(90000, 8000, 5),  -- Michael Davis
(85000, 7500, 6),  -- Emily Wilson
(95000, 8500, 7),  -- David Martinez

-- Salaries for Finance Department
(80000, 6000, 8),  -- Laura Taylor
(85000, 7000, 9),  -- James Anderson
(78000, 5000, 10), -- Patricia Thomas

-- Salaries for Marketing Department
(75000, 5500, 11),  -- Karen Moore
(73000, 5200, 12),  -- Robert Jackson
(72000, 5000, 13),  -- Lisa White

-- Salaries for Human Resources Department
(70000, 4500, 14),  -- Brian Harris
(68000, 4300, 15),  -- Jennifer Martin
(71000, 4600, 16);  -- William Thompson
'''

execute(query)

#### Insert initial data into Timesheets

In [17]:
# Insert initial data into Timesheets

query ='''
-- Insert data into Timesheets table corresponding to the updated Employees and Projects
INSERT INTO Timesheets (EmployeeID, ProjectID, WorkDate, HoursWorked) VALUES
-- Engineering Department
(5, 1, '2023-06-01', 8),  -- Michael Davis worked on Website Redesign
(6, 1, '2023-06-02', 7),  -- Emily Wilson worked on Website Redesign
(7, 1, '2023-06-03', 6),  -- David Martinez worked on Website Redesign

-- Finance Department
(8, 2, '2023-02-15', 6),  -- Laura Taylor worked on Financial Audit
(9, 2, '2023-02-16', 7),  -- James Anderson worked on Financial Audit
(10, 2, '2023-02-17', 5), -- Patricia Thomas worked on Financial Audit

-- HR Department
(14, 3, '2023-05-01', 8),  -- Brian Harris worked on HR System Upgrade
(15, 3, '2023-05-02', 7),  -- Jennifer Martin worked on HR System Upgrade
(16, 3, '2023-05-03', 6),  -- William Thompson worked on HR System Upgrade

-- Marketing Department
(11, 1, '2023-06-10', 4),  -- Karen Moore worked on Website Redesign
(12, 1, '2023-06-11', 5),  -- Robert Jackson worked on Website Redesign
(13, 1, '2023-06-12', 3);  -- Lisa White worked on Website Redesign

'''

execute(query)

# **SQL Practice Questions**

#### 1. Retrieve all employees' full names and hire dates.

In [18]:
query = '''
Select FirstName ||' '|| LastName as 'Full Name', HireDate from Employees;
'''
executedf(query)

       Full Name   HireDate
        John Doe 2010-06-01
       Bob Brown 2005-11-30
   Alice Johnson 2008-04-22
     Susan Clark 2006-07-15
   Michael Davis 2016-01-18
    Emily Wilson 2018-03-25
  David Martinez 2012-07-01
    Laura Taylor 2013-10-09
  James Anderson 2009-04-03
 Patricia Thomas 2017-11-05
     Karen Moore 2011-09-17
  Robert Jackson 2015-12-11
      Lisa White 2014-06-22
    Brian Harris 2007-05-20
 Jennifer Martin 2017-08-14
William Thompson 2010-10-30

#### 2. List all departments and their locations.

In [19]:
query = '''
Select DepartmentName, Location from Departments;
'''
executedf(query)

 DepartmentName      Location
Human Resources      New York
        Finance San Francisco
    Engineering        Austin
      Marketing       Chicago

#### 3. Get the names of all projects that started after January 1, 2023.

In [20]:
query = '''
Select * from Projects
where StartDate>'2023-01-01';
'''
executedf(query)

 ProjectID       ProjectName  StartDate    EndDate  DepartmentID
         1  Website Redesign 2023-01-15 2023-06-30             4
         2   Financial Audit 2023-02-01 2023-03-31             2
         3 HR System Upgrade 2023-05-01 2023-08-15             1
         4   Cloud Migration 2023-03-01 2023-09-30             3
         5   Market Research 2023-04-01 2023-07-31             4

#### 4. Find the total number of employees in each department.

In [21]:
query = '''
Select DepartmentName, Count(*) as 'Number of employees'
from Employees
left join Departments on employees.DepartmentID == Departments.DepartmentID
Group by DepartmentName;
'''
executedf(query)

 DepartmentName  Number of employees
    Engineering                    4
        Finance                    4
Human Resources                    4
      Marketing                    4

#### 5. Select the employees who were hired in 2015.

In [22]:
query = '''
Select FirstName, HireDate from Employees where HireDate>='2015-01-01' and HireDate <= '2015-12-31';
'''
executedf(query)

FirstName   HireDate
   Robert 2015-12-11

In [23]:
query= '''
select * from Employees
'''
executedf(query)

 EmployeeID FirstName LastName Gender  BirthDate   HireDate  DepartmentID  SalaryID  ManagerID
          1      John      Doe   Male 1985-05-15 2010-06-01             3         1        NaN
          2       Bob    Brown   Male 1978-03-25 2005-11-30             2         2        NaN
          3     Alice  Johnson Female 1982-01-14 2008-04-22             4         3        NaN
          4     Susan    Clark Female 1979-10-02 2006-07-15             1         4        NaN
          5   Michael    Davis   Male 1992-03-11 2016-01-18             3         5        1.0
          6     Emily   Wilson Female 1994-05-23 2018-03-25             3         6        1.0
          7     David Martinez   Male 1987-11-12 2012-07-01             3         7        1.0
          8     Laura   Taylor Female 1989-08-19 2013-10-09             2         8        2.0
          9     James Anderson   Male 1986-02-28 2009-04-03             2         9        2.0
         10  Patricia   Thomas Female 1991-12-22 2017-11-05             2        10        2.0
         11     Karen    Moore Female 1983-07-14 2011-09-17             4        11        3.0
         12    Robert  Jackson   Male 1990-06-30 2015-12-11             4        12        3.0
         13      Lisa    White Female 1988-04-27 2014-06-22             4        13        3.0
         14     Brian   Harris   Male 1981-09-07 2007-05-20             1        14        4.0
         15  Jennifer   Martin Female 1993-01-09 2017-08-14             1        15        4.0
         16   William Thompson   Male 1985-12-13 2010-10-30             1        16        4.0

#### 6. Retrieve the names of employees who work under a specific manager.

In [24]:
query = '''
Select e.Firstname||' '||e.lastName as 'Employee',m.FirstName as 'Manager'
from Employees e join Employees m on e.ManagerID = m.EmployeeID;
'''
executedf(query)

        Employee Manager
   Michael Davis    John
    Emily Wilson    John
  David Martinez    John
    Laura Taylor     Bob
  James Anderson     Bob
 Patricia Thomas     Bob
     Karen Moore   Alice
  Robert Jackson   Alice
      Lisa White   Alice
    Brian Harris   Susan
 Jennifer Martin   Susan
William Thompson   Susan

#### 7. Show the average salary in each department.

In [25]:
query = '''
Select d.DepartmentName as 'Department Name', avg(s.BaseSalary) as 'Average Salary'
  from Salaries s join Employees e on s.EmployeeID = e.EmployeeID join Departments d on e.DepartmentID = d.DepartmentID
  Group by d.DepartmentName;
'''
executedf(query)

Department Name  Average Salary
    Engineering         97500.0
        Finance         89500.0
Human Resources         78500.0
      Marketing         82500.0

#### 8. List all employees along with their department names.

In [26]:
query = '''
Select e.FirstName||' '||e.LastName as 'Employee Name', d.DepartmentName as 'Department'
  from Employees e join Departments d on e.DepartmentID = d.DepartmentID;
'''
executedf(query)

   Employee Name      Department
        John Doe     Engineering
       Bob Brown         Finance
   Alice Johnson       Marketing
     Susan Clark Human Resources
   Michael Davis     Engineering
    Emily Wilson     Engineering
  David Martinez     Engineering
    Laura Taylor         Finance
  James Anderson         Finance
 Patricia Thomas         Finance
     Karen Moore       Marketing
  Robert Jackson       Marketing
      Lisa White       Marketing
    Brian Harris Human Resources
 Jennifer Martin Human Resources
William Thompson Human Resources

#### 9. Get the total number of hours worked by each employee on all projects.

In [27]:
query = '''
Select e.FirstName||' '||e.LastName as 'Employee_Name', p.ProjectName as 'Project_Name', t.HoursWorked as 'Hours_Worked'
  from Employees e join Timesheets t on e.EmployeeID = T.EmployeeID join Projects p on t.ProjectID = p.ProjectID
  Order by Employee_Name;
'''
executedf(query)

   Employee_Name      Project_Name  Hours_Worked
    Brian Harris HR System Upgrade           8.0
  David Martinez  Website Redesign           6.0
    Emily Wilson  Website Redesign           7.0
  James Anderson   Financial Audit           7.0
 Jennifer Martin HR System Upgrade           7.0
     Karen Moore  Website Redesign           4.0
    Laura Taylor   Financial Audit           6.0
      Lisa White  Website Redesign           3.0
   Michael Davis  Website Redesign           8.0
 Patricia Thomas   Financial Audit           5.0
  Robert Jackson  Website Redesign           5.0
William Thompson HR System Upgrade           6.0

#### 10. Find all employees whose last name starts with 'J'.

In [28]:
query = '''
Select LastName, Firstname
  from Employees
  Where LastName LIKE 'J%';
'''
executedf(query)

LastName FirstName
 Johnson     Alice
 Jackson    Robert

##### verify

In [29]:
query = '''
Select *
  from Employees
Order by LastName;
'''
executedf(query)

 EmployeeID FirstName LastName Gender  BirthDate   HireDate  DepartmentID  SalaryID  ManagerID
          9     James Anderson   Male 1986-02-28 2009-04-03             2         9        2.0
          2       Bob    Brown   Male 1978-03-25 2005-11-30             2         2        NaN
          4     Susan    Clark Female 1979-10-02 2006-07-15             1         4        NaN
          5   Michael    Davis   Male 1992-03-11 2016-01-18             3         5        1.0
          1      John      Doe   Male 1985-05-15 2010-06-01             3         1        NaN
         14     Brian   Harris   Male 1981-09-07 2007-05-20             1        14        4.0
         12    Robert  Jackson   Male 1990-06-30 2015-12-11             4        12        3.0
          3     Alice  Johnson Female 1982-01-14 2008-04-22             4         3        NaN
         15  Jennifer   Martin Female 1993-01-09 2017-08-14             1        15        4.0
          7     David Martinez   Male 1987-11-12 2012-07-01             3         7        1.0
         11     Karen    Moore Female 1983-07-14 2011-09-17             4        11        3.0
          8     Laura   Taylor Female 1989-08-19 2013-10-09             2         8        2.0
         10  Patricia   Thomas Female 1991-12-22 2017-11-05             2        10        2.0
         16   William Thompson   Male 1985-12-13 2010-10-30             1        16        4.0
         13      Lisa    White Female 1988-04-27 2014-06-22             4        13        3.0
          6     Emily   Wilson Female 1994-05-23 2018-03-25             3         6        1.0

#### 11. Find the employee with the highest salary.

In [30]:
query = '''
Select e.FirstName||' '||e.LastName as 'Employee_Name', s.BaseSalary as 'Salary'
  from Employees e join Salaries s on e.EmployeeID = s.EmployeeID
  Order by s.BaseSalary desc;
'''
executedf(query)

   Employee_Name   Salary
        John Doe 120000.0
       Bob Brown 115000.0
   Alice Johnson 110000.0
     Susan Clark 105000.0
  David Martinez  95000.0
   Michael Davis  90000.0
    Emily Wilson  85000.0
  James Anderson  85000.0
    Laura Taylor  80000.0
 Patricia Thomas  78000.0
     Karen Moore  75000.0
  Robert Jackson  73000.0
      Lisa White  72000.0
William Thompson  71000.0
    Brian Harris  70000.0
 Jennifer Martin  68000.0

#### 12. List all projects along with the department name they belong to.

In [31]:
query = '''
Select ProjectName, DepartmentName
from Projects p left join Departments d on p.DepartmentID = d.DepartmentID;
'''
executedf(query)

      ProjectName  DepartmentName
 Website Redesign       Marketing
  Financial Audit         Finance
HR System Upgrade Human Resources
  Cloud Migration     Engineering
  Market Research       Marketing

#### 13. Get the employees who have worked on the 'Website Redesign' project.

In [32]:
query = '''
Select e.Firstname||' '||e.LastName as 'Employee_Name', p.ProjectName as 'Project_Name'
from Employees e left join Projects p on e.DepartmentID = p.DepartmentID
where ProjectName = 'Website Redesign';
'''
executedf(query)

 Employee_Name     Project_Name
 Alice Johnson Website Redesign
   Karen Moore Website Redesign
    Lisa White Website Redesign
Robert Jackson Website Redesign

#### 14. Calculate the total bonus paid to employees in the 'Finance' department.

In [33]:
query = '''
Select d.DepartmentName as 'Department_Name', sum(s.Bonus) as 'Total_Bonus'
from Employees e join Salaries s on e.EmployeeID = s.EmployeeID join Departments d on e.DepartmentID = d.DepartmentID
where d.DepartmentName = 'Finance'
Group by d.DepartmentName
;
'''
executedf(query)

Department_Name  Total_Bonus
        Finance      32000.0

#### 15. Retrieve the projects that have not ended yet.

In [34]:
query = '''
Select *
from Projects
where EndDate>'2024-08-15';
'''
executedf(query)

Empty DataFrame
Columns: [ProjectID, ProjectName, StartDate, EndDate, DepartmentID]
Index: []

#### 16. Find the total number of employees managed by each manager.

In [35]:
query = '''
Select m.FirstName||' '||m.LastName as 'ManagerName', count(e.FirstName||' '||e.LastName) as 'Number_Of_Employee'
from Employees e join Employees m on e.ManagerID = m.EmployeeID
group by ManagerName;
'''
executedf(query)

  ManagerName  Number_Of_Employee
Alice Johnson                   3
    Bob Brown                   3
     John Doe                   3
  Susan Clark                   3

#### 17. List employees who have never worked on any project.

In [36]:
query = '''
Select e.FirstName||' '||e.LastName as 'Employee_Name', p.ProjectName, p.StartDate, p.EndDate
from Employees e left join Timesheets t on e.EmployeeID = t.EmployeeID join Projects p on t.ProjectID = p.ProjectID
where ProjectName = "";
'''
executedf(query)

# All employees have work any some project

Empty DataFrame
Columns: [Employee_Name, ProjectName, StartDate, EndDate]
Index: []

##### Verify

In [37]:
query = '''
Select e.FirstName||' '||e.LastName as 'Employee_Name', p.ProjectName, p.StartDate, p.EndDate
from Employees e left join Timesheets t on e.EmployeeID = t.EmployeeID join Projects p on t.ProjectID = p.ProjectID;
'''
executedf(query)

   Employee_Name       ProjectName  StartDate    EndDate
   Michael Davis  Website Redesign 2023-01-15 2023-06-30
    Emily Wilson  Website Redesign 2023-01-15 2023-06-30
  David Martinez  Website Redesign 2023-01-15 2023-06-30
    Laura Taylor   Financial Audit 2023-02-01 2023-03-31
  James Anderson   Financial Audit 2023-02-01 2023-03-31
 Patricia Thomas   Financial Audit 2023-02-01 2023-03-31
    Brian Harris HR System Upgrade 2023-05-01 2023-08-15
 Jennifer Martin HR System Upgrade 2023-05-01 2023-08-15
William Thompson HR System Upgrade 2023-05-01 2023-08-15
     Karen Moore  Website Redesign 2023-01-15 2023-06-30
  Robert Jackson  Website Redesign 2023-01-15 2023-06-30
      Lisa White  Website Redesign 2023-01-15 2023-06-30

In [38]:
query = '''
Select e.FirstName||' '||e.LastName as 'Employee_Name', p.ProjectName, p.StartDate, p.EndDate
from Employees e left join Timesheets t on e.EmployeeID = t.EmployeeID join Projects p on t.ProjectID = p.ProjectID;
'''
df = pd.read_sql_query(query, sqliteConnection)
df

       Employee_Name        ProjectName   StartDate     EndDate
0      Michael Davis   Website Redesign  2023-01-15  2023-06-30
1       Emily Wilson   Website Redesign  2023-01-15  2023-06-30
2     David Martinez   Website Redesign  2023-01-15  2023-06-30
3       Laura Taylor    Financial Audit  2023-02-01  2023-03-31
4     James Anderson    Financial Audit  2023-02-01  2023-03-31
5    Patricia Thomas    Financial Audit  2023-02-01  2023-03-31
6       Brian Harris  HR System Upgrade  2023-05-01  2023-08-15
7    Jennifer Martin  HR System Upgrade  2023-05-01  2023-08-15
8   William Thompson  HR System Upgrade  2023-05-01  2023-08-15
9        Karen Moore   Website Redesign  2023-01-15  2023-06-30
10    Robert Jackson   Website Redesign  2023-01-15  2023-06-30
11        Lisa White   Website Redesign  2023-01-15  2023-06-30

#### 18. Get the departments with more than three employees.

In [39]:
query = '''
Select d.DepartmentName, count(EmployeeID) as 'Number_of_employees'
from Departments d left join Employees e on d.DepartmentID = e.DepartmentID
group by DepartmentName
having Number_of_employees>3;
'''
df = pd.read_sql_query(query, sqliteConnection)
df

    DepartmentName  Number_of_employees
0      Engineering                    4
1          Finance                    4
2  Human Resources                    4
3        Marketing                    4

#### 19. Find employees who were hired before their managers.

In [40]:
query = '''
Select e.FirstName||' '||e.LastName as 'EmployeeName', e.HireDate as 'Epmloyee_Hiring_date', m.FirstName||' '||m.LastName as 'ManagerName', m.HireDate as 'Manager_Hiring_Date'
from Employees e left join Employees m on e.ManagerID = m.EmployeeID
where e.HireDate < m.HireDate;
'''
df = pd.read_sql_query(query, sqliteConnection)
df

# No eomployees were hired before their mangers

Empty DataFrame
Columns: [EmployeeName, Epmloyee_Hiring_date, ManagerName, Manager_Hiring_Date]
Index: []

##### verify

In [41]:
query = '''
Select e.FirstName||' '||e.LastName as 'EmployeeName', e.HireDate as 'Epmloyee_Hiring_date', m.FirstName||' '||m.LastName as 'ManagerName', m.HireDate as 'Manager_Hiring_Date'
from Employees e left join Employees m on e.ManagerID = m.EmployeeID
where e.HireDate > m.HireDate;
'''
df = pd.read_sql_query(query, sqliteConnection)
df

        EmployeeName Epmloyee_Hiring_date    ManagerName Manager_Hiring_Date
0      Michael Davis           2016-01-18       John Doe          2010-06-01
1       Emily Wilson           2018-03-25       John Doe          2010-06-01
2     David Martinez           2012-07-01       John Doe          2010-06-01
3       Laura Taylor           2013-10-09      Bob Brown          2005-11-30
4     James Anderson           2009-04-03      Bob Brown          2005-11-30
5    Patricia Thomas           2017-11-05      Bob Brown          2005-11-30
6        Karen Moore           2011-09-17  Alice Johnson          2008-04-22
7     Robert Jackson           2015-12-11  Alice Johnson          2008-04-22
8         Lisa White           2014-06-22  Alice Johnson          2008-04-22
9       Brian Harris           2007-05-20    Susan Clark          2006-07-15
10   Jennifer Martin           2017-08-14    Susan Clark          2006-07-15
11  William Thompson           2010-10-30    Susan Clark          2006-07-15

#### 20. Calculate the total salary cost (including bonuses) for each department.

In [42]:
query = '''
select d.DepartmentName, sum(s.BaseSalary + s.Bonus) as 'Total_Salary (including bonuses)'
from Salaries s
join Employees e ON s.EmployeeID = e.EmployeeID
join Departments d on e.DepartmentID = d.DepartmentID
group by DepartmentName;
'''
df = pd.read_sql_query(query, sqliteConnection)
df

    DepartmentName  Total_Salary (including bonuses)
0      Engineering                          429000.0
1          Finance                          390000.0
2  Human Resources                          339400.0
3        Marketing                          358700.0

#### 21. Find employees who work on more than one project.

In [43]:
query = '''
Select e.FirstName||' '||e.LastName as 'EmployeeName', count(p.ProjectName) as 'Number_of_Projects'
from Employees e
join Timesheets t on e.EmployeeID = T.EmployeeID
join Projects p on p.ProjectID = t.ProjectID
group by EmployeeName
having Number_of_Projects >1;
'''
df = pd.read_sql_query(query, sqliteConnection)
df

# none of the employees have worked on more than one project

Empty DataFrame
Columns: [EmployeeName, Number_of_Projects]
Index: []

##### Verify

In [44]:
query = '''
Select e.FirstName||' '||e.LastName as 'EmployeeName', count(p.ProjectName) as 'Number_of_Projects'
from Employees e
join Timesheets t on e.EmployeeID = T.EmployeeID
join Projects p on p.ProjectID = t.ProjectID
group by EmployeeName;
'''
df = pd.read_sql_query(query, sqliteConnection)
df

        EmployeeName  Number_of_Projects
0       Brian Harris                   1
1     David Martinez                   1
2       Emily Wilson                   1
3     James Anderson                   1
4    Jennifer Martin                   1
5        Karen Moore                   1
6       Laura Taylor                   1
7         Lisa White                   1
8      Michael Davis                   1
9    Patricia Thomas                   1
10    Robert Jackson                   1
11  William Thompson                   1

#### 22. List the top 3 highest-paid employees in the company.

In [45]:
query = '''
Select e.FirstName||' '||e.LastName as 'EmployeeName', s.BaseSalary + s.Bonus as 'Salary'
from Employees e
join Salaries s on e.EmployeeID = s.EmployeeID
order by Salary desc
limit 3;
'''
df = pd.read_sql_query(query, sqliteConnection)
df

    EmployeeName    Salary
0       John Doe  135000.0
1      Bob Brown  129000.0
2  Alice Johnson  123000.0

##### verify

In [46]:
query = '''
Select e.FirstName||' '||e.LastName as 'EmployeeName', s.BaseSalary + s.Bonus as 'Salary'
from Employees e
join Salaries s on e.EmployeeID = s.EmployeeID
order by Salary desc;
'''
df = pd.read_sql_query(query, sqliteConnection)
df

        EmployeeName    Salary
0           John Doe  135000.0
1          Bob Brown  129000.0
2      Alice Johnson  123000.0
3        Susan Clark  117000.0
4     David Martinez  103500.0
5      Michael Davis   98000.0
6       Emily Wilson   92500.0
7     James Anderson   92000.0
8       Laura Taylor   86000.0
9    Patricia Thomas   83000.0
10       Karen Moore   80500.0
11    Robert Jackson   78200.0
12        Lisa White   77000.0
13  William Thompson   75600.0
14      Brian Harris   74500.0
15   Jennifer Martin   72300.0

#### 23. Get the department with the highest average employee salary.

In [47]:
query = '''
Select d.DepartmentName, avg(s.BaseSalary + s.Bonus) as 'Average_Salary'
from Employees e
join Salaries s on e.EmployeeID = s.EmployeeID
join Departments d on e.DepartmentID = d.DepartmentID
group by DepartmentName
order by Average_Salary desc
limit 1
;
'''
df = pd.read_sql_query(query, sqliteConnection)
df

  DepartmentName  Average_Salary
0    Engineering        107250.0

##### verify

In [48]:
query = '''
Select d.DepartmentName, avg(s.BaseSalary + s.Bonus) as 'Average_Salary'
from Employees e
join Salaries s on e.EmployeeID = s.EmployeeID
join Departments d on e.DepartmentID = d.DepartmentID
group by DepartmentName
order by Average_Salary desc;
'''
df = pd.read_sql_query(query, sqliteConnection)
df

    DepartmentName  Average_Salary
0      Engineering        107250.0
1          Finance         97500.0
2        Marketing         89675.0
3  Human Resources         84850.0

#### 24. Retrieve the total number of hours worked on each project by department.

In [49]:
query = '''
Select d.DepartmentName, sum(t.HoursWorked) 'Total_Hours_by_Department'
from Employees e
join Timesheets t on t.EmployeeID = e.EmployeeID
join Departments d on e.DepartmentID = d.DepartmentID
group by DepartmentName;
'''
df = pd.read_sql_query(query, sqliteConnection)
df

    DepartmentName  Total_Hours_by_Department
0      Engineering                       21.0
1          Finance                       18.0
2  Human Resources                       21.0
3        Marketing                       12.0

##### Verify

In [50]:
query = '''
Select d.DepartmentName, t.HoursWorked
from Employees e
join Timesheets t on t.EmployeeID = e.EmployeeID
join Departments d on e.DepartmentID = d.DepartmentID
;
'''
df = pd.read_sql_query(query, sqliteConnection)
df

     DepartmentName  HoursWorked
0       Engineering          8.0
1       Engineering          7.0
2       Engineering          6.0
3           Finance          6.0
4           Finance          7.0
5           Finance          5.0
6   Human Resources          8.0
7   Human Resources          7.0
8   Human Resources          6.0
9         Marketing          4.0
10        Marketing          5.0
11        Marketing          3.0

#### 25. Find all employees who have not received a bonus.

In [51]:
query = '''
Select e.FirstName||' '||e.LastName as 'Epmoyee_Name', s.Bonus
from Employees e
join Salaries s on s.EmployeeID = e.EmployeeID
where bonus <=0
;
'''
df = pd.read_sql_query(query, sqliteConnection)
df

# All of the employees have received bonus.

Empty DataFrame
Columns: [Epmoyee_Name, Bonus]
Index: []

##### Verify

In [52]:
query = '''
Select e.FirstName||' '||e.LastName as 'Epmoyee_Name', s.Bonus
from Employees e
join Salaries s on s.EmployeeID = e.EmployeeID
;
'''
df = pd.read_sql_query(query, sqliteConnection)
df

        Epmoyee_Name    Bonus
0           John Doe  15000.0
1          Bob Brown  14000.0
2      Alice Johnson  13000.0
3        Susan Clark  12000.0
4      Michael Davis   8000.0
5       Emily Wilson   7500.0
6     David Martinez   8500.0
7       Laura Taylor   6000.0
8     James Anderson   7000.0
9    Patricia Thomas   5000.0
10       Karen Moore   5500.0
11    Robert Jackson   5200.0
12        Lisa White   5000.0
13      Brian Harris   4500.0
14   Jennifer Martin   4300.0
15  William Thompson   4600.0

#### 26. Get the total hours worked by employees in the 'Engineering' department in 2023.

In [53]:
query = '''
Select d.Departmentname, sum(t.Hoursworked) as 'Hoursworked', strftime('%Y', WorkDate) AS Year
from Employees e
join Departments d on d.DepartmentID = e.DepartmentID
left join Timesheets t on t.EmployeeID = e.EmployeeID
where DepartmentName = 'Engineering' and workdate like '2023%'
group by Departmentname
;
'''
df = pd.read_sql_query(query, sqliteConnection)
df

  DepartmentName  Hoursworked  Year
0    Engineering         21.0  2023

#### 27. List projects that have more than one department involved.

In [54]:
query = '''
Select e.FirstName||' '||e.LastName as 'Epmoyee_Name', count(DepartmentName) as 'Count_of_DepartmentName'
from Employees e
join Departments d on d.DepartmentID = e.DepartmentID
group by Epmoyee_Name
having Count_of_DepartmentName >1
;
'''
df = pd.read_sql_query(query, sqliteConnection)
df

Empty DataFrame
Columns: [Epmoyee_Name, Count_of_DepartmentName]
Index: []

##### Verify

In [55]:
query = '''
Select e.FirstName||' '||e.LastName as 'Epmoyee_Name', count(DepartmentName) as 'Count_of_DepartmentName'
from Employees e
join Departments d on d.DepartmentID = e.DepartmentID
group by Epmoyee_Name
;
'''
df = pd.read_sql_query(query, sqliteConnection)
df

        Epmoyee_Name  Count_of_DepartmentName
0      Alice Johnson                        1
1          Bob Brown                        1
2       Brian Harris                        1
3     David Martinez                        1
4       Emily Wilson                        1
5     James Anderson                        1
6    Jennifer Martin                        1
7           John Doe                        1
8        Karen Moore                        1
9       Laura Taylor                        1
10        Lisa White                        1
11     Michael Davis                        1
12   Patricia Thomas                        1
13    Robert Jackson                        1
14       Susan Clark                        1
15  William Thompson                        1

#### 28. Find the managers who manage more than one department.

In [56]:
query = '''
Select e.FirstName||' '||e.LastName as 'Manager_Name', count(DepartmentName) as 'Count_of_DepartmentName'
from Employees e
join Departments d on d.DepartmentID = e.DepartmentID
where e.ManagerID IS Null
group by Manager_Name
having Count_of_DepartmentName >1;
'''
df = pd.read_sql_query(query, sqliteConnection)
df

Empty DataFrame
Columns: [Manager_Name, Count_of_DepartmentName]
Index: []

##### Verify

In [57]:
query = '''
Select e.FirstName||' '||e.LastName as 'Manager_Name', count(DepartmentName) as 'Count_of_DepartmentName'
from Employees e
join Departments d on d.DepartmentID = e.DepartmentID
where e.ManagerID IS Null
group by Manager_Name
;
'''
df = pd.read_sql_query(query, sqliteConnection)
df

    Manager_Name  Count_of_DepartmentName
0  Alice Johnson                        1
1      Bob Brown                        1
2       John Doe                        1
3    Susan Clark                        1

#### 29. Calculate the total work hours recorded in the Timesheets table.

In [58]:
query = '''
Select sum(HoursWorked) as 'HoursWorked'
from Timesheets
;
'''
df = pd.read_sql_query(query, sqliteConnection)
df

   HoursWorked
0         72.0

#### 30. Retrieve employees who were hired in the last 5 years and have a base salary above the company average.

In [59]:
query = '''
Select e.FirstName||' '||e.LastName as 'Employee_Name', e.HireDate, s.BaseSalary, (Select avg(basesalary) from salaries) as 'Average_Base_Salary'
from Employees e
join salaries s on e.EmployeeID = s.EmployeeID
where hiredate < (SELECT DATE(MAX(e2.HireDate), '-5 years') FROM Employees e2) and BaseSalary > Average_Base_Salary;
'''
df = pd.read_sql_query(query, sqliteConnection)
print(df)
print('Date consiedration: Last hire date - 5 Years')

    Employee_Name    HireDate  BaseSalary  Average_Base_Salary
0        John Doe  2010-06-01    120000.0              87000.0
1       Bob Brown  2005-11-30    115000.0              87000.0
2   Alice Johnson  2008-04-22    110000.0              87000.0
3     Susan Clark  2006-07-15    105000.0              87000.0
4  David Martinez  2012-07-01     95000.0              87000.0
Date consiedration: Last hire date - 5 Years